// ============================================================
// Data Loader — Housing Near Hospitals
//
// Reads JSON data files generated by import scripts.
// In development, falls back to sample-data.ts if JSON files
// don't exist yet (gradual migration).
//
// This module is the bridge between the data pipeline
// (scripts that output JSON) and the Next.js app.
// ============================================================

import * as fs from "fs";
import * as path from "path";
import type { Hospital, GsaPerDiemRate, HudSafmrRate } from "@/types";

const DATA_DIR = path.join(process.cwd(), "data");

/**
 * Read and parse a JSON data file. Returns null if file doesn't exist.
 */
function readJsonFile<T>(filename: string): T | null {
  const filePath = path.join(DATA_DIR, filename);
  try {
    if (!fs.existsSync(filePath)) return null;
    const content = fs.readFileSync(filePath, "utf-8");
    return JSON.parse(content) as T;
  } catch {
    console.warn(`Warning: failed to read ${filePath}`);
    return null;
  }
}

// ============================================================
// Hospital Data
// ============================================================

interface HospitalJsonRecord {
  id: string;
  hifldId: string;
  metroId: string;
  name: string;
  slug: string;
  address?: string;
  city?: string;
  stateCode?: string;
  zipCode?: string;
  county?: string;
  phone?: string;
  website?: string;
  location: { lat: number; lng: number };
  hospitalType: string;
  ownership?: string;
  bedCount?: number;
  totalStaff?: number;
  hasEmergency?: boolean;
  traumaLevel?: string;
  hasHelipad?: boolean;
  isActive: boolean;
  // CMS enrichment
  cmsCcn?: string;
  cmsOverallRating?: number | null;
  cmsMortality?: string | null;
  cmsReadmission?: string | null;
  cmsSafetyRating?: string | null;
  cmsPatientExp?: string | null;
}

/**
 * Load hospitals from data/hospitals.json.
 * Returns null if the file doesn't exist (caller should fall back to sample data).
 */
export function loadHospitals(): Hospital[] | null {
  const records = readJsonFile<HospitalJsonRecord[]>("hospitals.json");
  if (!records) return null;

  return records.map((r) => ({
    id: r.id,
    hifldId: r.hifldId,
    metroId: r.metroId,
    cmsCcn: r.cmsCcn,
    name: r.name,
    slug: r.slug,
    address: r.address,
    city: r.city,
    stateCode: r.stateCode,
    zipCode: r.zipCode,
    phone: r.phone,
    website: r.website,
    location: r.location,
    hospitalType: r.hospitalType as Hospital["hospitalType"],
    ownership: r.ownership,
    bedCount: r.bedCount ?? undefined,
    hasEmergency: r.hasEmergency ?? true,
    traumaLevel: r.traumaLevel ?? undefined,
    cmsOverallRating: r.cmsOverallRating ?? undefined,
    cmsMortality: r.cmsMortality ?? undefined,
    cmsReadmission: r.cmsReadmission ?? undefined,
    isActive: r.isActive,
  }));
}

// ============================================================
// GSA Per Diem Rates
// ============================================================

interface GsaJsonFile {
  fiscalYear: number;
  conusStandard: { lodgingRate: number; mieRate: number };
  metroRates: Array<{
    state: string;
    city: string;
    county: string;
    lodgingRate: number;
    mieRate: number;
    isNonStandard: boolean;
  }>;
}

/**
 * Load GSA per-diem rates from data/gsa-perdiem.json.
 */
export function loadGsaRates(): GsaPerDiemRate[] | null {
  const data = readJsonFile<GsaJsonFile>("gsa-perdiem.json");
  if (!data) return null;

  return data.metroRates.map((r) => ({
    fiscalYear: data.fiscalYear,
    state: r.state,
    city: r.city,
    county: r.county,
    lodgingRate: r.lodgingRate,
    mieRate: r.mieRate,
    isNonStandard: r.isNonStandard,
  }));
}

// ============================================================
// HUD SAFMR Rates
// ============================================================

interface SafmrJsonFile {
  fiscalYear: number;
  rates: Array<{
    zipCode: string;
    city: string;
    state: string;
    metroId: string;
    efficiency: number;
    oneBedroom: number;
    twoBedroom: number;
    threeBedroom: number;
    fourBedroom: number;
    year: number;
  }>;
}

/**
 * Load HUD SAFMR rates from data/hud-safmr.json.
 */
export function loadSafmrRates(): HudSafmrRate[] | null {
  const data = readJsonFile<SafmrJsonFile>("hud-safmr.json");
  if (!data) return null;

  return data.rates.map((r) => ({
    zipCode: r.zipCode,
    year: r.year,
    efficiency: r.efficiency,
    oneBedroom: r.oneBedroom,
    twoBedroom: r.twoBedroom,
    threeBedroom: r.threeBedroom,
    fourBedroom: r.fourBedroom,
    metroAreaName: `${r.city}, ${r.state}`,
  }));
}

/**
 * Look up SAFMR for a specific ZIP code.
 */
export function getSafmrByZip(zipCode: string): HudSafmrRate | null {
  const rates = loadSafmrRates();
  if (!rates) return null;
  return rates.find((r) => r.zipCode === zipCode) ?? null;
}

// ============================================================
// Summary / Status
// ============================================================

export interface DataPipelineStatus {
  hospitals: { loaded: boolean; count: number };
  gsaRates: { loaded: boolean; count: number };
  safmrRates: { loaded: boolean; count: number };
}

/**
 * Check what data files are available.
 */
export function getDataPipelineStatus(): DataPipelineStatus {
  const hospitals = loadHospitals();
  const gsaRates = loadGsaRates();
  const safmrRates = loadSafmrRates();

  return {
    hospitals: { loaded: hospitals !== null, count: hospitals?.length ?? 0 },
    gsaRates: { loaded: gsaRates !== null, count: gsaRates?.length ?? 0 },
    safmrRates: { loaded: safmrRates !== null, count: safmrRates?.length ?? 0 },
  };
}
