// ============================================================
// Sample Data for Development — Housing Near Hospitals
// Real hospital names and approximate coordinates
// ============================================================

import type { Hospital, Listing, Metro } from "@/types";

export const SAMPLE_METROS: Metro[] = [
  {
    id: "metro-nashville",
    slug: "nashville-tn",
    name: "Nashville, TN",
    stateCode: "TN",
    center: { lat: 36.1627, lng: -86.7816 },
    radiusMiles: 30,
    timezone: "America/Chicago",
    circuityFactor: 1.3,
    isActive: true,
    metroPop: 1989519,
    avgRent1br: 1550,
    costOfLiving: 97.5,
  },
  {
    id: "metro-houston",
    slug: "houston-tx",
    name: "Houston, TX",
    stateCode: "TX",
    center: { lat: 29.7604, lng: -95.3698 },
    radiusMiles: 30,
    timezone: "America/Chicago",
    circuityFactor: 1.4,
    isActive: true,
    metroPop: 7122240,
    avgRent1br: 1200,
    costOfLiving: 93.1,
  },
  {
    id: "metro-phoenix",
    slug: "phoenix-az",
    name: "Phoenix, AZ",
    stateCode: "AZ",
    center: { lat: 33.4484, lng: -112.074 },
    radiusMiles: 30,
    timezone: "America/Phoenix",
    circuityFactor: 1.25,
    isActive: true,
    metroPop: 4845832,
    avgRent1br: 1350,
    costOfLiving: 100.8,
  },
];

export const SAMPLE_HOSPITALS: Hospital[] = [
  // Nashville
  {
    id: "hosp-vanderbilt",
    metroId: "metro-nashville",
    name: "Vanderbilt University Medical Center",
    slug: "vanderbilt-university-medical-center",
    address: "1211 Medical Center Dr",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37232",
    location: { lat: 36.1425, lng: -86.8026 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "Vanderbilt Health",
    bedCount: 1091,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 4,
    isActive: true,
  },
  {
    id: "hosp-tristar-centennial",
    metroId: "metro-nashville",
    name: "TriStar Centennial Medical Center",
    slug: "tristar-centennial-medical-center",
    address: "2300 Patterson St",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37203",
    location: { lat: 36.1483, lng: -86.8083 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    systemName: "HCA Healthcare",
    bedCount: 657,
    hasEmergency: true,
    traumaLevel: "Level II",
    teachingStatus: "Minor",
    cmsOverallRating: 3,
    isActive: true,
  },
  {
    id: "hosp-saint-thomas-west",
    metroId: "metro-nashville",
    name: "Ascension Saint Thomas West",
    slug: "ascension-saint-thomas-west",
    address: "4220 Harding Pike",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37205",
    location: { lat: 36.1298, lng: -86.8496 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "Ascension",
    bedCount: 541,
    hasEmergency: true,
    traumaLevel: "Level II",
    teachingStatus: "Minor",
    cmsOverallRating: 3,
    isActive: true,
  },
  {
    id: "hosp-monroe-carell",
    metroId: "metro-nashville",
    name: "Monroe Carell Jr. Children's Hospital at Vanderbilt",
    slug: "monroe-carell-childrens-hospital",
    address: "2200 Children's Way",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37232",
    location: { lat: 36.1433, lng: -86.8012 },
    hospitalType: "Children's",
    ownership: "Non-Profit",
    systemName: "Vanderbilt Health",
    bedCount: 271,
    hasEmergency: true,
    teachingStatus: "Major",
    cmsOverallRating: 5,
    isActive: true,
  },
  {
    id: "hosp-tristar-skyline",
    metroId: "metro-nashville",
    name: "TriStar Skyline Medical Center",
    slug: "tristar-skyline-medical-center",
    address: "3441 Dickerson Pike",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37207",
    location: { lat: 36.2161, lng: -86.7601 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    systemName: "HCA Healthcare",
    bedCount: 274,
    hasEmergency: true,
    traumaLevel: "Level III",
    cmsOverallRating: 3,
    isActive: true,
  },
  // Houston
  {
    id: "hosp-houston-methodist",
    metroId: "metro-houston",
    name: "Houston Methodist Hospital",
    slug: "houston-methodist-hospital",
    address: "6565 Fannin St",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77030",
    location: { lat: 29.7104, lng: -95.3985 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "Houston Methodist",
    bedCount: 946,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 5,
    isActive: true,
  },
  {
    id: "hosp-memorial-hermann-tmc",
    metroId: "metro-houston",
    name: "Memorial Hermann - Texas Medical Center",
    slug: "memorial-hermann-texas-medical-center",
    address: "6411 Fannin St",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77030",
    location: { lat: 29.7088, lng: -95.3969 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "Memorial Hermann",
    bedCount: 1076,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 4,
    isActive: true,
  },
  {
    id: "hosp-md-anderson",
    metroId: "metro-houston",
    name: "MD Anderson Cancer Center",
    slug: "md-anderson-cancer-center",
    address: "1515 Holcombe Blvd",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77030",
    location: { lat: 29.7075, lng: -95.3966 },
    hospitalType: "General Acute Care",
    ownership: "Government",
    systemName: "UT System",
    bedCount: 668,
    hasEmergency: false,
    teachingStatus: "Major",
    cmsOverallRating: 5,
    isActive: true,
  },
  {
    id: "hosp-ben-taub",
    metroId: "metro-houston",
    name: "Ben Taub Hospital",
    slug: "ben-taub-hospital",
    address: "1504 Taub Loop",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77030",
    location: { lat: 29.7060, lng: -95.3972 },
    hospitalType: "General Acute Care",
    ownership: "Government",
    systemName: "Harris Health System",
    bedCount: 586,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 3,
    isActive: true,
  },
  // Phoenix
  {
    id: "hosp-mayo-phoenix",
    metroId: "metro-phoenix",
    name: "Mayo Clinic Hospital - Phoenix",
    slug: "mayo-clinic-hospital-phoenix",
    address: "5777 E Mayo Blvd",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85054",
    location: { lat: 33.6596, lng: -111.9563 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "Mayo Clinic",
    bedCount: 304,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 5,
    isActive: true,
  },
  {
    id: "hosp-banner-university",
    metroId: "metro-phoenix",
    name: "Banner - University Medical Center Phoenix",
    slug: "banner-university-medical-center-phoenix",
    address: "1111 E McDowell Rd",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85006",
    location: { lat: 33.4585, lng: -112.0536 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "Banner Health",
    bedCount: 734,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 4,
    isActive: true,
  },
  {
    id: "hosp-honorhealth-scottsdale",
    metroId: "metro-phoenix",
    name: "HonorHealth Scottsdale Osborn Medical Center",
    slug: "honorhealth-scottsdale-osborn",
    address: "7400 E Osborn Rd",
    city: "Scottsdale",
    stateCode: "AZ",
    zipCode: "85251",
    location: { lat: 33.4772, lng: -111.9237 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "HonorHealth",
    bedCount: 347,
    hasEmergency: true,
    traumaLevel: "Level II",
    cmsOverallRating: 4,
    isActive: true,
  },
];

// Sample listings near Nashville hospitals
export const SAMPLE_LISTINGS: Listing[] = [
  {
    id: "list-1",
    metroId: "metro-nashville",
    source: "manual",
    title: "Modern 1BR in Midtown — Walk to Vanderbilt",
    description: "Fully furnished 1-bedroom apartment in the heart of Midtown Nashville. 10-minute walk to Vanderbilt Medical Center. W/D in unit, free parking spot included.",
    propertyType: "apartment",
    location: { lat: 36.1520, lng: -86.7970 },
    address: "1800 Broadway",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37203",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 720,
    priceMonthly: 1850,
    isFurnished: true,
    leaseMinMonths: 3,
    allowsPets: true,
    hasParking: true,
    hasInUnitLaundry: true,
    amenities: ["pool", "gym", "balcony", "doorman"],
    primaryImageUrl: "/images/sample/apt-1.jpg",
    imageCount: 8,
    listingQualityScore: 85,
    status: "active",
    isVerified: true,
  },
  {
    id: "list-2",
    metroId: "metro-nashville",
    source: "manual",
    title: "Cozy Studio near Music Row — Furnished",
    description: "Charming furnished studio on Music Row. Quick commute to all major Nashville hospitals. Perfect for travel nurses on 13-week contracts.",
    propertyType: "studio",
    location: { lat: 36.1495, lng: -86.7928 },
    address: "33 Music Square W",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37203",
    bedrooms: 0,
    bathrooms: 1,
    sqft: 475,
    priceMonthly: 1350,
    isFurnished: true,
    leaseMinMonths: 1,
    allowsPets: false,
    hasParking: true,
    hasInUnitLaundry: false,
    amenities: ["gym", "rooftop"],
    primaryImageUrl: "/images/sample/apt-2.jpg",
    imageCount: 5,
    listingQualityScore: 70,
    status: "active",
    isVerified: true,
  },
  {
    id: "list-3",
    metroId: "metro-nashville",
    source: "manual",
    title: "Spacious 2BR in Sylvan Park — 5 min to St. Thomas",
    description: "Beautiful 2-bedroom home in the quiet Sylvan Park neighborhood. 5-minute drive to Ascension Saint Thomas West. Fenced backyard, pet friendly.",
    propertyType: "house",
    location: { lat: 36.1380, lng: -86.8360 },
    address: "4512 Nevada Ave",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37209",
    bedrooms: 2,
    bathrooms: 1.5,
    sqft: 1100,
    priceMonthly: 2200,
    isFurnished: false,
    leaseMinMonths: 6,
    allowsPets: true,
    hasParking: true,
    hasInUnitLaundry: true,
    amenities: ["backyard", "storage", "porch"],
    primaryImageUrl: "/images/sample/house-1.jpg",
    imageCount: 12,
    listingQualityScore: 60,
    status: "active",
    isVerified: false,
  },
  {
    id: "list-4",
    metroId: "metro-nashville",
    source: "manual",
    title: "Luxury 1BR in The Gulch — All Amenities",
    description: "Upscale 1-bedroom in The Gulch with stunning downtown views. Walking distance to multiple hospitals. Full amenity package.",
    propertyType: "apartment",
    location: { lat: 36.1510, lng: -86.7870 },
    address: "600 12th Ave S",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37203",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 800,
    priceMonthly: 2400,
    isFurnished: true,
    leaseMinMonths: 3,
    allowsPets: true,
    hasParking: true,
    hasInUnitLaundry: true,
    amenities: ["pool", "gym", "rooftop", "concierge", "balcony"],
    primaryImageUrl: "/images/sample/apt-3.jpg",
    imageCount: 15,
    listingQualityScore: 90,
    status: "active",
    isVerified: true,
  },
  {
    id: "list-5",
    metroId: "metro-nashville",
    source: "manual",
    title: "Affordable Room in West End — Near Hospitals",
    description: "Private room in shared house near West End. 2 miles from Vanderbilt. All utilities included. Great for residents on a budget.",
    propertyType: "room",
    location: { lat: 36.1465, lng: -86.8140 },
    address: "2800 West End Ave",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37203",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 280,
    priceMonthly: 850,
    isFurnished: true,
    leaseMinMonths: 1,
    allowsPets: false,
    hasParking: true,
    hasInUnitLaundry: true,
    amenities: ["utilities-included", "wifi"],
    primaryImageUrl: "/images/sample/room-1.jpg",
    imageCount: 4,
    listingQualityScore: 65,
    status: "active",
    isVerified: false,
  },
  {
    id: "list-6",
    metroId: "metro-nashville",
    source: "manual",
    title: "2BR Townhouse in Berry Hill — Short Term OK",
    description: "Nice townhouse in Berry Hill with private garage. 10 min to all midtown hospitals. Short-term lease available for travel nurses.",
    propertyType: "townhouse",
    location: { lat: 36.1200, lng: -86.7650 },
    address: "2610 Berry Hill Dr",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37204",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1250,
    priceMonthly: 1950,
    isFurnished: false,
    leaseMinMonths: 3,
    allowsPets: true,
    hasParking: true,
    hasInUnitLaundry: true,
    amenities: ["garage", "patio", "storage"],
    primaryImageUrl: "/images/sample/townhouse-1.jpg",
    imageCount: 9,
    listingQualityScore: 55,
    status: "active",
    isVerified: true,
  },
];
