// ============================================================
// Sample Data for Development — Housing Near Hospitals
// Real hospital names and approximate coordinates
// ============================================================

import type { Hospital, Listing, Metro } from "@/types";

export const SAMPLE_METROS: Metro[] = [
  {
    id: "metro-nashville",
    slug: "nashville-tn",
    name: "Nashville, TN",
    stateCode: "TN",
    center: { lat: 36.1627, lng: -86.7816 },
    radiusMiles: 30,
    timezone: "America/Chicago",
    circuityFactor: 1.3,
    isActive: true,
    metroPop: 1989519,
    avgRent1br: 1550,
    costOfLiving: 97.5,
  },
  {
    id: "metro-houston",
    slug: "houston-tx",
    name: "Houston, TX",
    stateCode: "TX",
    center: { lat: 29.7604, lng: -95.3698 },
    radiusMiles: 30,
    timezone: "America/Chicago",
    circuityFactor: 1.4,
    isActive: true,
    metroPop: 7122240,
    avgRent1br: 1200,
    costOfLiving: 93.1,
  },
  {
    id: "metro-phoenix",
    slug: "phoenix-az",
    name: "Phoenix, AZ",
    stateCode: "AZ",
    center: { lat: 33.4484, lng: -112.074 },
    radiusMiles: 30,
    timezone: "America/Phoenix",
    circuityFactor: 1.25,
    isActive: true,
    metroPop: 4845832,
    avgRent1br: 1350,
    costOfLiving: 100.8,
  },
  {
    id: "metro-atlanta",
    slug: "atlanta-ga",
    name: "Atlanta, GA",
    stateCode: "GA",
    center: { lat: 33.749, lng: -84.388 },
    radiusMiles: 30,
    timezone: "America/New_York",
    circuityFactor: 1.35,
    isActive: true,
    metroPop: 6144050,
    avgRent1br: 1650,
    costOfLiving: 101.3,
  },
  {
    id: "metro-tampa",
    slug: "tampa-fl",
    name: "Tampa-St. Petersburg, FL",
    stateCode: "FL",
    center: { lat: 27.9506, lng: -82.4572 },
    radiusMiles: 30,
    timezone: "America/New_York",
    circuityFactor: 1.3,
    isActive: true,
    metroPop: 3175275,
    avgRent1br: 1550,
    costOfLiving: 99.8,
  },
  {
    id: "metro-charlotte",
    slug: "charlotte-nc",
    name: "Charlotte, NC",
    stateCode: "NC",
    center: { lat: 35.2271, lng: -80.8431 },
    radiusMiles: 30,
    timezone: "America/New_York",
    circuityFactor: 1.3,
    isActive: true,
    metroPop: 2660329,
    avgRent1br: 1450,
    costOfLiving: 96.2,
  },
  {
    id: "metro-dallas",
    slug: "dallas-tx",
    name: "Dallas-Fort Worth, TX",
    stateCode: "TX",
    center: { lat: 32.7767, lng: -96.797 },
    radiusMiles: 35,
    timezone: "America/Chicago",
    circuityFactor: 1.35,
    isActive: true,
    metroPop: 7637387,
    avgRent1br: 1400,
    costOfLiving: 95.5,
  },
  {
    id: "metro-denver",
    slug: "denver-co",
    name: "Denver, CO",
    stateCode: "CO",
    center: { lat: 39.7392, lng: -104.9903 },
    radiusMiles: 30,
    timezone: "America/Denver",
    circuityFactor: 1.3,
    isActive: true,
    metroPop: 2963821,
    avgRent1br: 1650,
    costOfLiving: 107.2,
  },
  {
    id: "metro-minneapolis",
    slug: "minneapolis-mn",
    name: "Minneapolis-St. Paul, MN",
    stateCode: "MN",
    center: { lat: 44.9778, lng: -93.265 },
    radiusMiles: 30,
    timezone: "America/Chicago",
    circuityFactor: 1.3,
    isActive: true,
    metroPop: 3690261,
    avgRent1br: 1350,
    costOfLiving: 99.1,
  },
  {
    id: "metro-san-antonio",
    slug: "san-antonio-tx",
    name: "San Antonio, TX",
    stateCode: "TX",
    center: { lat: 29.4241, lng: -98.4936 },
    radiusMiles: 30,
    timezone: "America/Chicago",
    circuityFactor: 1.3,
    isActive: true,
    metroPop: 2558143,
    avgRent1br: 1100,
    costOfLiving: 90.8,
  },
];

export const SAMPLE_HOSPITALS: Hospital[] = [
  // Nashville
  {
    id: "hosp-vanderbilt",
    metroId: "metro-nashville",
    name: "Vanderbilt University Medical Center",
    slug: "vanderbilt-university-medical-center",
    address: "1211 Medical Center Dr",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37232",
    location: { lat: 36.1425, lng: -86.8026 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "Vanderbilt Health",
    bedCount: 1091,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 4,
    isActive: true,
  },
  {
    id: "hosp-tristar-centennial",
    metroId: "metro-nashville",
    name: "TriStar Centennial Medical Center",
    slug: "tristar-centennial-medical-center",
    address: "2300 Patterson St",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37203",
    location: { lat: 36.1483, lng: -86.8083 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    systemName: "HCA Healthcare",
    bedCount: 657,
    hasEmergency: true,
    traumaLevel: "Level II",
    teachingStatus: "Minor",
    cmsOverallRating: 3,
    isActive: true,
  },
  {
    id: "hosp-saint-thomas-west",
    metroId: "metro-nashville",
    name: "Ascension Saint Thomas West",
    slug: "ascension-saint-thomas-west",
    address: "4220 Harding Pike",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37205",
    location: { lat: 36.1298, lng: -86.8496 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "Ascension",
    bedCount: 541,
    hasEmergency: true,
    traumaLevel: "Level II",
    teachingStatus: "Minor",
    cmsOverallRating: 3,
    isActive: true,
  },
  {
    id: "hosp-monroe-carell",
    metroId: "metro-nashville",
    name: "Monroe Carell Jr. Children's Hospital at Vanderbilt",
    slug: "monroe-carell-childrens-hospital",
    address: "2200 Children's Way",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37232",
    location: { lat: 36.1433, lng: -86.8012 },
    hospitalType: "Children's",
    ownership: "Non-Profit",
    systemName: "Vanderbilt Health",
    bedCount: 271,
    hasEmergency: true,
    teachingStatus: "Major",
    cmsOverallRating: 5,
    isActive: true,
  },
  {
    id: "hosp-tristar-skyline",
    metroId: "metro-nashville",
    name: "TriStar Skyline Medical Center",
    slug: "tristar-skyline-medical-center",
    address: "3441 Dickerson Pike",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37207",
    location: { lat: 36.2161, lng: -86.7601 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    systemName: "HCA Healthcare",
    bedCount: 274,
    hasEmergency: true,
    traumaLevel: "Level III",
    cmsOverallRating: 3,
    isActive: true,
  },
  // Houston
  {
    id: "hosp-houston-methodist",
    metroId: "metro-houston",
    name: "Houston Methodist Hospital",
    slug: "houston-methodist-hospital",
    address: "6565 Fannin St",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77030",
    location: { lat: 29.7104, lng: -95.3985 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "Houston Methodist",
    bedCount: 946,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 5,
    isActive: true,
  },
  {
    id: "hosp-memorial-hermann-tmc",
    metroId: "metro-houston",
    name: "Memorial Hermann - Texas Medical Center",
    slug: "memorial-hermann-texas-medical-center",
    address: "6411 Fannin St",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77030",
    location: { lat: 29.7088, lng: -95.3969 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "Memorial Hermann",
    bedCount: 1076,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 4,
    isActive: true,
  },
  {
    id: "hosp-md-anderson",
    metroId: "metro-houston",
    name: "MD Anderson Cancer Center",
    slug: "md-anderson-cancer-center",
    address: "1515 Holcombe Blvd",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77030",
    location: { lat: 29.7075, lng: -95.3966 },
    hospitalType: "General Acute Care",
    ownership: "Government",
    systemName: "UT System",
    bedCount: 668,
    hasEmergency: false,
    teachingStatus: "Major",
    cmsOverallRating: 5,
    isActive: true,
  },
  {
    id: "hosp-ben-taub",
    metroId: "metro-houston",
    name: "Ben Taub Hospital",
    slug: "ben-taub-hospital",
    address: "1504 Taub Loop",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77030",
    location: { lat: 29.7060, lng: -95.3972 },
    hospitalType: "General Acute Care",
    ownership: "Government",
    systemName: "Harris Health System",
    bedCount: 586,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 3,
    isActive: true,
  },
  // Phoenix
  {
    id: "hosp-mayo-phoenix",
    metroId: "metro-phoenix",
    name: "Mayo Clinic Hospital - Phoenix",
    slug: "mayo-clinic-hospital-phoenix",
    address: "5777 E Mayo Blvd",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85054",
    location: { lat: 33.6596, lng: -111.9563 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "Mayo Clinic",
    bedCount: 304,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 5,
    isActive: true,
  },
  {
    id: "hosp-banner-university",
    metroId: "metro-phoenix",
    name: "Banner - University Medical Center Phoenix",
    slug: "banner-university-medical-center-phoenix",
    address: "1111 E McDowell Rd",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85006",
    location: { lat: 33.4585, lng: -112.0536 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "Banner Health",
    bedCount: 734,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 4,
    isActive: true,
  },
  {
    id: "hosp-honorhealth-scottsdale",
    metroId: "metro-phoenix",
    name: "HonorHealth Scottsdale Osborn Medical Center",
    slug: "honorhealth-scottsdale-osborn",
    address: "7400 E Osborn Rd",
    city: "Scottsdale",
    stateCode: "AZ",
    zipCode: "85251",
    location: { lat: 33.4772, lng: -111.9237 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "HonorHealth",
    bedCount: 347,
    hasEmergency: true,
    traumaLevel: "Level II",
    cmsOverallRating: 4,
    isActive: true,
  },
  // Atlanta
  {
    id: "hosp-emory-university",
    metroId: "metro-atlanta",
    name: "Emory University Hospital",
    slug: "emory-university-hospital",
    address: "1364 Clifton Rd NE",
    city: "Atlanta",
    stateCode: "GA",
    zipCode: "30322",
    location: { lat: 33.7946, lng: -84.3233 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "Emory Healthcare",
    bedCount: 733,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 5,
    isActive: true,
  },
  {
    id: "hosp-grady-memorial",
    metroId: "metro-atlanta",
    name: "Grady Memorial Hospital",
    slug: "grady-memorial-hospital",
    address: "80 Jesse Hill Jr Dr SE",
    city: "Atlanta",
    stateCode: "GA",
    zipCode: "30303",
    location: { lat: 33.7536, lng: -84.3839 },
    hospitalType: "General Acute Care",
    ownership: "Government",
    systemName: "Grady Health System",
    bedCount: 953,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 3,
    isActive: true,
  },
  {
    id: "hosp-piedmont-atlanta",
    metroId: "metro-atlanta",
    name: "Piedmont Atlanta Hospital",
    slug: "piedmont-atlanta-hospital",
    address: "1968 Peachtree Rd NW",
    city: "Atlanta",
    stateCode: "GA",
    zipCode: "30309",
    location: { lat: 33.8048, lng: -84.3829 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "Piedmont Healthcare",
    bedCount: 529,
    hasEmergency: true,
    traumaLevel: "Level II",
    teachingStatus: "Minor",
    cmsOverallRating: 4,
    isActive: true,
  },
  {
    id: "hosp-northside-atlanta",
    metroId: "metro-atlanta",
    name: "Northside Hospital Atlanta",
    slug: "northside-hospital-atlanta",
    address: "1000 Johnson Ferry Rd NE",
    city: "Atlanta",
    stateCode: "GA",
    zipCode: "30342",
    location: { lat: 33.8776, lng: -84.3563 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "Northside Hospital",
    bedCount: 621,
    hasEmergency: true,
    cmsOverallRating: 4,
    isActive: true,
  },
  // Tampa-St. Petersburg
  {
    id: "hosp-tampa-general",
    metroId: "metro-tampa",
    name: "Tampa General Hospital",
    slug: "tampa-general-hospital",
    address: "1 Tampa General Cir",
    city: "Tampa",
    stateCode: "FL",
    zipCode: "33606",
    location: { lat: 27.9374, lng: -82.4537 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "Tampa General",
    bedCount: 1041,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 4,
    isActive: true,
  },
  {
    id: "hosp-moffitt-cancer",
    metroId: "metro-tampa",
    name: "H. Lee Moffitt Cancer Center",
    slug: "moffitt-cancer-center",
    address: "12902 USF Magnolia Dr",
    city: "Tampa",
    stateCode: "FL",
    zipCode: "33612",
    location: { lat: 28.0643, lng: -82.4318 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "Moffitt Cancer Center",
    bedCount: 206,
    hasEmergency: false,
    teachingStatus: "Major",
    cmsOverallRating: 5,
    isActive: true,
  },
  {
    id: "hosp-adventhealth-tampa",
    metroId: "metro-tampa",
    name: "AdventHealth Tampa",
    slug: "adventhealth-tampa",
    address: "3100 E Fletcher Ave",
    city: "Tampa",
    stateCode: "FL",
    zipCode: "33613",
    location: { lat: 28.0735, lng: -82.4120 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "AdventHealth",
    bedCount: 537,
    hasEmergency: true,
    traumaLevel: "Level II",
    cmsOverallRating: 4,
    isActive: true,
  },
  {
    id: "hosp-st-josephs-tampa",
    metroId: "metro-tampa",
    name: "St. Joseph's Hospital",
    slug: "st-josephs-hospital-tampa",
    address: "3001 W Dr Martin Luther King Jr Blvd",
    city: "Tampa",
    stateCode: "FL",
    zipCode: "33607",
    location: { lat: 27.9904, lng: -82.4894 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "BayCare Health System",
    bedCount: 882,
    hasEmergency: true,
    traumaLevel: "Level II",
    cmsOverallRating: 3,
    isActive: true,
  },
  // Charlotte
  {
    id: "hosp-atrium-cmc",
    metroId: "metro-charlotte",
    name: "Atrium Health Carolinas Medical Center",
    slug: "atrium-health-carolinas-medical-center",
    address: "1000 Blythe Blvd",
    city: "Charlotte",
    stateCode: "NC",
    zipCode: "28203",
    location: { lat: 35.2030, lng: -80.8398 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "Advocate Health (Atrium)",
    bedCount: 1379,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 4,
    isActive: true,
  },
  {
    id: "hosp-novant-presbyterian",
    metroId: "metro-charlotte",
    name: "Novant Health Presbyterian Medical Center",
    slug: "novant-health-presbyterian-medical-center",
    address: "200 Hawthorne Ln",
    city: "Charlotte",
    stateCode: "NC",
    zipCode: "28204",
    location: { lat: 35.2168, lng: -80.8297 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "Novant Health",
    bedCount: 601,
    hasEmergency: true,
    traumaLevel: "Level II",
    teachingStatus: "Minor",
    cmsOverallRating: 4,
    isActive: true,
  },
  {
    id: "hosp-atrium-pineville",
    metroId: "metro-charlotte",
    name: "Atrium Health Pineville",
    slug: "atrium-health-pineville",
    address: "10628 Park Rd",
    city: "Charlotte",
    stateCode: "NC",
    zipCode: "28134",
    location: { lat: 35.0850, lng: -80.8700 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "Advocate Health (Atrium)",
    bedCount: 235,
    hasEmergency: true,
    cmsOverallRating: 3,
    isActive: true,
  },
  // Dallas-Fort Worth
  {
    id: "hosp-parkland",
    metroId: "metro-dallas",
    name: "Parkland Memorial Hospital",
    slug: "parkland-memorial-hospital",
    address: "5200 Harry Hines Blvd",
    city: "Dallas",
    stateCode: "TX",
    zipCode: "75235",
    location: { lat: 32.8120, lng: -96.8384 },
    hospitalType: "General Acute Care",
    ownership: "Government",
    systemName: "Parkland Health",
    bedCount: 862,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 3,
    isActive: true,
  },
  {
    id: "hosp-baylor-dallas",
    metroId: "metro-dallas",
    name: "Baylor University Medical Center",
    slug: "baylor-university-medical-center",
    address: "3500 Gaston Ave",
    city: "Dallas",
    stateCode: "TX",
    zipCode: "75246",
    location: { lat: 32.7869, lng: -96.7769 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "Baylor Scott & White",
    bedCount: 914,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 4,
    isActive: true,
  },
  {
    id: "hosp-ut-southwestern",
    metroId: "metro-dallas",
    name: "UT Southwestern Medical Center",
    slug: "ut-southwestern-medical-center",
    address: "5323 Harry Hines Blvd",
    city: "Dallas",
    stateCode: "TX",
    zipCode: "75235",
    location: { lat: 32.8136, lng: -96.8412 },
    hospitalType: "General Acute Care",
    ownership: "Government",
    systemName: "UT Southwestern",
    bedCount: 740,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 5,
    isActive: true,
  },
  {
    id: "hosp-cook-childrens",
    metroId: "metro-dallas",
    name: "Cook Children's Medical Center",
    slug: "cook-childrens-medical-center",
    address: "801 7th Ave",
    city: "Fort Worth",
    stateCode: "TX",
    zipCode: "76104",
    location: { lat: 32.7340, lng: -97.3267 },
    hospitalType: "Children's",
    ownership: "Non-Profit",
    systemName: "Cook Children's",
    bedCount: 458,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 5,
    isActive: true,
  },
  // Denver
  {
    id: "hosp-uchealth-anschutz",
    metroId: "metro-denver",
    name: "UCHealth University of Colorado Hospital",
    slug: "uchealth-university-of-colorado-hospital",
    address: "12605 E 16th Ave",
    city: "Aurora",
    stateCode: "CO",
    zipCode: "80045",
    location: { lat: 39.7454, lng: -104.8384 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "UCHealth",
    bedCount: 680,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 5,
    isActive: true,
  },
  {
    id: "hosp-denver-health",
    metroId: "metro-denver",
    name: "Denver Health Medical Center",
    slug: "denver-health-medical-center",
    address: "777 Bannock St",
    city: "Denver",
    stateCode: "CO",
    zipCode: "80204",
    location: { lat: 39.7267, lng: -104.9977 },
    hospitalType: "General Acute Care",
    ownership: "Government",
    systemName: "Denver Health",
    bedCount: 525,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 3,
    isActive: true,
  },
  {
    id: "hosp-national-jewish",
    metroId: "metro-denver",
    name: "National Jewish Health",
    slug: "national-jewish-health",
    address: "1400 Jackson St",
    city: "Denver",
    stateCode: "CO",
    zipCode: "80206",
    location: { lat: 39.7394, lng: -104.9422 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "National Jewish Health",
    bedCount: 118,
    hasEmergency: false,
    teachingStatus: "Major",
    cmsOverallRating: 5,
    isActive: true,
  },
  {
    id: "hosp-st-joseph-denver",
    metroId: "metro-denver",
    name: "St. Joseph Hospital",
    slug: "st-joseph-hospital-denver",
    address: "1375 E 19th Ave",
    city: "Denver",
    stateCode: "CO",
    zipCode: "80218",
    location: { lat: 39.7456, lng: -104.9690 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "SCL Health / Intermountain",
    bedCount: 365,
    hasEmergency: true,
    traumaLevel: "Level II",
    teachingStatus: "Minor",
    cmsOverallRating: 4,
    isActive: true,
  },
  // Minneapolis-St. Paul
  {
    id: "hosp-abbott-northwestern",
    metroId: "metro-minneapolis",
    name: "Abbott Northwestern Hospital",
    slug: "abbott-northwestern-hospital",
    address: "800 E 28th St",
    city: "Minneapolis",
    stateCode: "MN",
    zipCode: "55407",
    location: { lat: 44.9534, lng: -93.2614 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "Allina Health",
    bedCount: 627,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 4,
    isActive: true,
  },
  {
    id: "hosp-hennepin-county",
    metroId: "metro-minneapolis",
    name: "Hennepin County Medical Center",
    slug: "hennepin-county-medical-center",
    address: "701 Park Ave",
    city: "Minneapolis",
    stateCode: "MN",
    zipCode: "55415",
    location: { lat: 44.9723, lng: -93.2612 },
    hospitalType: "General Acute Care",
    ownership: "Government",
    systemName: "Hennepin Healthcare",
    bedCount: 484,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 3,
    isActive: true,
  },
  {
    id: "hosp-umn-medical",
    metroId: "metro-minneapolis",
    name: "University of Minnesota Medical Center",
    slug: "university-of-minnesota-medical-center",
    address: "500 SE Harvard St",
    city: "Minneapolis",
    stateCode: "MN",
    zipCode: "55455",
    location: { lat: 44.9721, lng: -93.2316 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "M Health Fairview",
    bedCount: 901,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 4,
    isActive: true,
  },
  {
    id: "hosp-regions-hospital",
    metroId: "metro-minneapolis",
    name: "Regions Hospital",
    slug: "regions-hospital",
    address: "640 Jackson St",
    city: "St. Paul",
    stateCode: "MN",
    zipCode: "55101",
    location: { lat: 44.9569, lng: -93.0892 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "HealthPartners",
    bedCount: 454,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 3,
    isActive: true,
  },
  // San Antonio
  {
    id: "hosp-bamc",
    metroId: "metro-san-antonio",
    name: "Brooke Army Medical Center (BAMC)",
    slug: "brooke-army-medical-center",
    address: "3551 Roger Brooke Dr",
    city: "San Antonio",
    stateCode: "TX",
    zipCode: "78234",
    location: { lat: 29.4602, lng: -98.4402 },
    hospitalType: "Military",
    ownership: "Government",
    systemName: "Department of Defense",
    bedCount: 425,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    isActive: true,
  },
  {
    id: "hosp-methodist-sa",
    metroId: "metro-san-antonio",
    name: "Methodist Hospital San Antonio",
    slug: "methodist-hospital-san-antonio",
    address: "7700 Floyd Curl Dr",
    city: "San Antonio",
    stateCode: "TX",
    zipCode: "78229",
    location: { lat: 29.5100, lng: -98.5730 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    systemName: "Methodist Healthcare",
    bedCount: 1536,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Minor",
    cmsOverallRating: 4,
    isActive: true,
  },
  {
    id: "hosp-university-health-sa",
    metroId: "metro-san-antonio",
    name: "University Hospital San Antonio",
    slug: "university-hospital-san-antonio",
    address: "4502 Medical Dr",
    city: "San Antonio",
    stateCode: "TX",
    zipCode: "78229",
    location: { lat: 29.5088, lng: -98.5693 },
    hospitalType: "General Acute Care",
    ownership: "Government",
    systemName: "University Health",
    bedCount: 716,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 3,
    isActive: true,
  },
  {
    id: "hosp-baptist-medical-sa",
    metroId: "metro-san-antonio",
    name: "Baptist Medical Center",
    slug: "baptist-medical-center-san-antonio",
    address: "111 Dallas St",
    city: "San Antonio",
    stateCode: "TX",
    zipCode: "78205",
    location: { lat: 29.4322, lng: -98.4853 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    systemName: "Tenet Healthcare",
    bedCount: 631,
    hasEmergency: true,
    traumaLevel: "Level III",
    cmsOverallRating: 3,
    isActive: true,
  },
];

// Sample listings near Nashville hospitals
export const SAMPLE_LISTINGS: Listing[] = [
  {
    id: "list-1",
    metroId: "metro-nashville",
    source: "manual",
    title: "Modern 1BR in Midtown — Walk to Vanderbilt",
    description: "Fully furnished 1-bedroom apartment in the heart of Midtown Nashville. 10-minute walk to Vanderbilt Medical Center. W/D in unit, free parking spot included.",
    propertyType: "apartment",
    location: { lat: 36.1520, lng: -86.7970 },
    address: "1800 Broadway",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37203",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 720,
    priceMonthly: 1850,
    isFurnished: true,
    leaseMinMonths: 3,
    allowsPets: true,
    hasParking: true,
    hasInUnitLaundry: true,
    amenities: ["pool", "gym", "balcony", "doorman"],
    primaryImageUrl: "/images/sample/apt-1.jpg",
    imageCount: 8,
    listingQualityScore: 85,
    status: "active",
    isVerified: true,
  },
  {
    id: "list-2",
    metroId: "metro-nashville",
    source: "manual",
    title: "Cozy Studio near Music Row — Furnished",
    description: "Charming furnished studio on Music Row. Quick commute to all major Nashville hospitals. Perfect for travel nurses on 13-week contracts.",
    propertyType: "studio",
    location: { lat: 36.1495, lng: -86.7928 },
    address: "33 Music Square W",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37203",
    bedrooms: 0,
    bathrooms: 1,
    sqft: 475,
    priceMonthly: 1350,
    isFurnished: true,
    leaseMinMonths: 1,
    allowsPets: false,
    hasParking: true,
    hasInUnitLaundry: false,
    amenities: ["gym", "rooftop"],
    primaryImageUrl: "/images/sample/apt-2.jpg",
    imageCount: 5,
    listingQualityScore: 70,
    status: "active",
    isVerified: true,
  },
  {
    id: "list-3",
    metroId: "metro-nashville",
    source: "manual",
    title: "Spacious 2BR in Sylvan Park — 5 min to St. Thomas",
    description: "Beautiful 2-bedroom home in the quiet Sylvan Park neighborhood. 5-minute drive to Ascension Saint Thomas West. Fenced backyard, pet friendly.",
    propertyType: "house",
    location: { lat: 36.1380, lng: -86.8360 },
    address: "4512 Nevada Ave",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37209",
    bedrooms: 2,
    bathrooms: 1.5,
    sqft: 1100,
    priceMonthly: 2200,
    isFurnished: false,
    leaseMinMonths: 6,
    allowsPets: true,
    hasParking: true,
    hasInUnitLaundry: true,
    amenities: ["backyard", "storage", "porch"],
    primaryImageUrl: "/images/sample/house-1.jpg",
    imageCount: 12,
    listingQualityScore: 60,
    status: "active",
    isVerified: false,
  },
  {
    id: "list-4",
    metroId: "metro-nashville",
    source: "manual",
    title: "Luxury 1BR in The Gulch — All Amenities",
    description: "Upscale 1-bedroom in The Gulch with stunning downtown views. Walking distance to multiple hospitals. Full amenity package.",
    propertyType: "apartment",
    location: { lat: 36.1510, lng: -86.7870 },
    address: "600 12th Ave S",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37203",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 800,
    priceMonthly: 2400,
    isFurnished: true,
    leaseMinMonths: 3,
    allowsPets: true,
    hasParking: true,
    hasInUnitLaundry: true,
    amenities: ["pool", "gym", "rooftop", "concierge", "balcony"],
    primaryImageUrl: "/images/sample/apt-3.jpg",
    imageCount: 15,
    listingQualityScore: 90,
    status: "active",
    isVerified: true,
  },
  {
    id: "list-5",
    metroId: "metro-nashville",
    source: "manual",
    title: "Affordable Room in West End — Near Hospitals",
    description: "Private room in shared house near West End. 2 miles from Vanderbilt. All utilities included. Great for residents on a budget.",
    propertyType: "room",
    location: { lat: 36.1465, lng: -86.8140 },
    address: "2800 West End Ave",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37203",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 280,
    priceMonthly: 850,
    isFurnished: true,
    leaseMinMonths: 1,
    allowsPets: false,
    hasParking: true,
    hasInUnitLaundry: true,
    amenities: ["utilities-included", "wifi"],
    primaryImageUrl: "/images/sample/room-1.jpg",
    imageCount: 4,
    listingQualityScore: 65,
    status: "active",
    isVerified: false,
  },
  {
    id: "list-6",
    metroId: "metro-nashville",
    source: "manual",
    title: "2BR Townhouse in Berry Hill — Short Term OK",
    description: "Nice townhouse in Berry Hill with private garage. 10 min to all midtown hospitals. Short-term lease available for travel nurses.",
    propertyType: "townhouse",
    location: { lat: 36.1200, lng: -86.7650 },
    address: "2610 Berry Hill Dr",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37204",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1250,
    priceMonthly: 1950,
    isFurnished: false,
    leaseMinMonths: 3,
    allowsPets: true,
    hasParking: true,
    hasInUnitLaundry: true,
    amenities: ["garage", "patio", "storage"],
    primaryImageUrl: "/images/sample/townhouse-1.jpg",
    imageCount: 9,
    listingQualityScore: 55,
    status: "active",
    isVerified: true,
  },
  // Houston
  {
    id: "list-7",
    metroId: "metro-houston",
    source: "manual",
    title: "Furnished 1BR in Texas Medical Center Area",
    description: "Fully furnished apartment steps from the Texas Medical Center. Perfect for travel nurses and residents. All utilities included.",
    propertyType: "apartment",
    location: { lat: 29.7130, lng: -95.3960 },
    address: "6700 Main St",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77030",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 680,
    priceMonthly: 1650,
    isFurnished: true,
    leaseMinMonths: 1,
    allowsPets: false,
    hasParking: true,
    hasInUnitLaundry: false,
    amenities: ["pool", "gym", "utilities-included"],
    primaryImageUrl: "/images/sample/apt-houston-1.jpg",
    imageCount: 6,
    listingQualityScore: 80,
    status: "active",
    isVerified: true,
  },
  {
    id: "list-8",
    metroId: "metro-houston",
    source: "manual",
    title: "Modern 2BR in Museum District — Near TMC",
    description: "Spacious 2-bedroom in the Museum District. 5 minutes to Texas Medical Center. Open floor plan with updated kitchen.",
    propertyType: "apartment",
    location: { lat: 29.7228, lng: -95.3904 },
    address: "4100 Montrose Blvd",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77006",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1050,
    priceMonthly: 2100,
    isFurnished: false,
    leaseMinMonths: 6,
    allowsPets: true,
    hasParking: true,
    hasInUnitLaundry: true,
    amenities: ["pool", "gym", "balcony", "storage"],
    primaryImageUrl: "/images/sample/apt-houston-2.jpg",
    imageCount: 10,
    listingQualityScore: 70,
    status: "active",
    isVerified: true,
  },
  {
    id: "list-9",
    metroId: "metro-houston",
    source: "manual",
    title: "Studio in Rice Village — Walk to Med Center",
    description: "Cozy studio in Rice Village. Walking distance to Houston Methodist and Memorial Hermann TMC. Furnished with month-to-month lease.",
    propertyType: "studio",
    location: { lat: 29.7160, lng: -95.4089 },
    address: "2500 University Blvd",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77005",
    bedrooms: 0,
    bathrooms: 1,
    sqft: 450,
    priceMonthly: 1250,
    isFurnished: true,
    leaseMinMonths: 1,
    allowsPets: false,
    hasParking: true,
    hasInUnitLaundry: false,
    amenities: ["gym", "rooftop", "wifi"],
    primaryImageUrl: "/images/sample/studio-houston-1.jpg",
    imageCount: 5,
    listingQualityScore: 75,
    status: "active",
    isVerified: false,
  },
  {
    id: "list-10",
    metroId: "metro-houston",
    source: "manual",
    title: "Private Room in Hermann Park Area",
    description: "Private room in a shared house near Hermann Park. Very close to all TMC hospitals. Quiet neighborhood, great for night shift workers.",
    propertyType: "room",
    location: { lat: 29.7140, lng: -95.3870 },
    address: "1900 Hermann Dr",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77004",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 300,
    priceMonthly: 850,
    isFurnished: true,
    leaseMinMonths: 1,
    allowsPets: false,
    hasParking: true,
    hasInUnitLaundry: true,
    amenities: ["utilities-included", "wifi", "backyard"],
    primaryImageUrl: "/images/sample/room-houston-1.jpg",
    imageCount: 4,
    listingQualityScore: 60,
    status: "active",
    isVerified: false,
  },
  // Phoenix
  {
    id: "list-11",
    metroId: "metro-phoenix",
    source: "manual",
    title: "Furnished 1BR in Scottsdale — Near HonorHealth",
    description: "Stylish furnished 1-bedroom apartment in downtown Scottsdale. Short walk to HonorHealth Scottsdale Osborn. Resort-style amenities.",
    propertyType: "apartment",
    location: { lat: 33.4795, lng: -111.9260 },
    address: "7300 E Indian School Rd",
    city: "Scottsdale",
    stateCode: "AZ",
    zipCode: "85251",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 750,
    priceMonthly: 1700,
    isFurnished: true,
    leaseMinMonths: 3,
    allowsPets: true,
    hasParking: true,
    hasInUnitLaundry: true,
    amenities: ["pool", "gym", "spa", "balcony"],
    primaryImageUrl: "/images/sample/apt-phoenix-1.jpg",
    imageCount: 8,
    listingQualityScore: 85,
    status: "active",
    isVerified: true,
  },
  {
    id: "list-12",
    metroId: "metro-phoenix",
    source: "manual",
    title: "2BR Condo near Banner University Medical Center",
    description: "Updated 2-bedroom condo in Roosevelt Row arts district. 5 minutes to Banner University Medical Center. W/D in unit.",
    propertyType: "condo",
    location: { lat: 33.4530, lng: -112.0640 },
    address: "725 N 3rd St",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85004",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 980,
    priceMonthly: 1900,
    isFurnished: false,
    leaseMinMonths: 6,
    allowsPets: true,
    hasParking: true,
    hasInUnitLaundry: true,
    amenities: ["pool", "gym", "rooftop"],
    primaryImageUrl: "/images/sample/condo-phoenix-1.jpg",
    imageCount: 11,
    listingQualityScore: 65,
    status: "active",
    isVerified: true,
  },
  {
    id: "list-13",
    metroId: "metro-phoenix",
    source: "manual",
    title: "Affordable Studio in Tempe — Furnished",
    description: "Budget-friendly furnished studio in Tempe near the Light Rail. Easy access to all major Phoenix hospitals. Utilities included.",
    propertyType: "studio",
    location: { lat: 33.4255, lng: -111.9400 },
    address: "600 S College Ave",
    city: "Tempe",
    stateCode: "AZ",
    zipCode: "85281",
    bedrooms: 0,
    bathrooms: 1,
    sqft: 420,
    priceMonthly: 1100,
    isFurnished: true,
    leaseMinMonths: 1,
    allowsPets: false,
    hasParking: false,
    hasInUnitLaundry: false,
    amenities: ["gym", "utilities-included", "wifi"],
    primaryImageUrl: "/images/sample/studio-phoenix-1.jpg",
    imageCount: 4,
    listingQualityScore: 70,
    status: "active",
    isVerified: false,
  },
  {
    id: "list-14",
    metroId: "metro-phoenix",
    source: "manual",
    title: "3BR House in North Phoenix — Near Mayo Clinic",
    description: "Spacious 3-bedroom house in a quiet North Phoenix neighborhood. 10-minute drive to Mayo Clinic Hospital. Large backyard, pet friendly.",
    propertyType: "house",
    location: { lat: 33.6400, lng: -111.9700 },
    address: "5500 E Deer Valley Dr",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85054",
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1600,
    priceMonthly: 2400,
    isFurnished: false,
    leaseMinMonths: 6,
    allowsPets: true,
    hasParking: true,
    hasInUnitLaundry: true,
    amenities: ["backyard", "garage", "patio", "storage"],
    primaryImageUrl: "/images/sample/house-phoenix-1.jpg",
    imageCount: 14,
    listingQualityScore: 60,
    status: "active",
    isVerified: true,
  },
];
