// ============================================================
// Sample Data for Development — Housing Near Hospitals
// Real hospital names and approximate coordinates
// ============================================================

import type { Hospital, Listing, Metro } from "@/types";

export const SAMPLE_METROS: Metro[] = [
  {
    id: "metro-nashville",
    slug: "nashville-tn",
    name: "Nashville, TN",
    stateCode: "TN",
    center: { lat: 36.1627, lng: -86.7816 },
    radiusMiles: 30,
    timezone: "America/Chicago",
    circuityFactor: 1.3,
    isActive: true,
    metroPop: 1989519,
    avgRent1br: 1550,
    costOfLiving: 97.5,
  },
  {
    id: "metro-houston",
    slug: "houston-tx",
    name: "Houston, TX",
    stateCode: "TX",
    center: { lat: 29.7604, lng: -95.3698 },
    radiusMiles: 30,
    timezone: "America/Chicago",
    circuityFactor: 1.4,
    isActive: true,
    metroPop: 7122240,
    avgRent1br: 1200,
    costOfLiving: 93.1,
  },
  {
    id: "metro-phoenix",
    slug: "phoenix-az",
    name: "Phoenix, AZ",
    stateCode: "AZ",
    center: { lat: 33.4484, lng: -112.074 },
    radiusMiles: 30,
    timezone: "America/Phoenix",
    circuityFactor: 1.25,
    isActive: true,
    metroPop: 4845832,
    avgRent1br: 1350,
    costOfLiving: 100.8,
  },
];

export const SAMPLE_HOSPITALS: Hospital[] = [
  // Nashville
  {
    id: "hosp-vanderbilt",
    metroId: "metro-nashville",
    name: "Vanderbilt University Medical Center",
    slug: "vanderbilt-university-medical-center",
    address: "1211 Medical Center Dr",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37232",
    location: { lat: 36.1425, lng: -86.8026 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "Vanderbilt Health",
    bedCount: 1091,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 4,
    isActive: true,
  },
  {
    id: "hosp-tristar-centennial",
    metroId: "metro-nashville",
    name: "TriStar Centennial Medical Center",
    slug: "tristar-centennial-medical-center",
    address: "2300 Patterson St",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37203",
    location: { lat: 36.1483, lng: -86.8083 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    systemName: "HCA Healthcare",
    bedCount: 657,
    hasEmergency: true,
    traumaLevel: "Level II",
    teachingStatus: "Minor",
    cmsOverallRating: 3,
    isActive: true,
  },
  {
    id: "hosp-saint-thomas-west",
    metroId: "metro-nashville",
    name: "Ascension Saint Thomas West",
    slug: "ascension-saint-thomas-west",
    address: "4220 Harding Pike",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37205",
    location: { lat: 36.1298, lng: -86.8496 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "Ascension",
    bedCount: 541,
    hasEmergency: true,
    traumaLevel: "Level II",
    teachingStatus: "Minor",
    cmsOverallRating: 3,
    isActive: true,
  },
  {
    id: "hosp-monroe-carell",
    metroId: "metro-nashville",
    name: "Monroe Carell Jr. Children's Hospital at Vanderbilt",
    slug: "monroe-carell-childrens-hospital",
    address: "2200 Children's Way",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37232",
    location: { lat: 36.1433, lng: -86.8012 },
    hospitalType: "Children's",
    ownership: "Non-Profit",
    systemName: "Vanderbilt Health",
    bedCount: 271,
    hasEmergency: true,
    teachingStatus: "Major",
    cmsOverallRating: 5,
    isActive: true,
  },
  {
    id: "hosp-tristar-skyline",
    metroId: "metro-nashville",
    name: "TriStar Skyline Medical Center",
    slug: "tristar-skyline-medical-center",
    address: "3441 Dickerson Pike",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37207",
    location: { lat: 36.2161, lng: -86.7601 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    systemName: "HCA Healthcare",
    bedCount: 274,
    hasEmergency: true,
    traumaLevel: "Level III",
    cmsOverallRating: 3,
    isActive: true,
  },
  // Houston
  {
    id: "hosp-houston-methodist",
    metroId: "metro-houston",
    name: "Houston Methodist Hospital",
    slug: "houston-methodist-hospital",
    address: "6565 Fannin St",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77030",
    location: { lat: 29.7104, lng: -95.3985 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "Houston Methodist",
    bedCount: 946,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 5,
    isActive: true,
  },
  {
    id: "hosp-memorial-hermann-tmc",
    metroId: "metro-houston",
    name: "Memorial Hermann - Texas Medical Center",
    slug: "memorial-hermann-texas-medical-center",
    address: "6411 Fannin St",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77030",
    location: { lat: 29.7088, lng: -95.3969 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "Memorial Hermann",
    bedCount: 1076,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 4,
    isActive: true,
  },
  {
    id: "hosp-md-anderson",
    metroId: "metro-houston",
    name: "MD Anderson Cancer Center",
    slug: "md-anderson-cancer-center",
    address: "1515 Holcombe Blvd",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77030",
    location: { lat: 29.7075, lng: -95.3966 },
    hospitalType: "General Acute Care",
    ownership: "Government",
    systemName: "UT System",
    bedCount: 668,
    hasEmergency: false,
    teachingStatus: "Major",
    cmsOverallRating: 5,
    isActive: true,
  },
  {
    id: "hosp-ben-taub",
    metroId: "metro-houston",
    name: "Ben Taub Hospital",
    slug: "ben-taub-hospital",
    address: "1504 Taub Loop",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77030",
    location: { lat: 29.7060, lng: -95.3972 },
    hospitalType: "General Acute Care",
    ownership: "Government",
    systemName: "Harris Health System",
    bedCount: 586,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 3,
    isActive: true,
  },
  // Phoenix
  {
    id: "hosp-mayo-phoenix",
    metroId: "metro-phoenix",
    name: "Mayo Clinic Hospital - Phoenix",
    slug: "mayo-clinic-hospital-phoenix",
    address: "5777 E Mayo Blvd",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85054",
    location: { lat: 33.6596, lng: -111.9563 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "Mayo Clinic",
    bedCount: 304,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 5,
    isActive: true,
  },
  {
    id: "hosp-banner-university",
    metroId: "metro-phoenix",
    name: "Banner - University Medical Center Phoenix",
    slug: "banner-university-medical-center-phoenix",
    address: "1111 E McDowell Rd",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85006",
    location: { lat: 33.4585, lng: -112.0536 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "Banner Health",
    bedCount: 734,
    hasEmergency: true,
    traumaLevel: "Level I",
    teachingStatus: "Major",
    cmsOverallRating: 4,
    isActive: true,
  },
  {
    id: "hosp-honorhealth-scottsdale",
    metroId: "metro-phoenix",
    name: "HonorHealth Scottsdale Osborn Medical Center",
    slug: "honorhealth-scottsdale-osborn",
    address: "7400 E Osborn Rd",
    city: "Scottsdale",
    stateCode: "AZ",
    zipCode: "85251",
    location: { lat: 33.4772, lng: -111.9237 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    systemName: "HonorHealth",
    bedCount: 347,
    hasEmergency: true,
    traumaLevel: "Level II",
    cmsOverallRating: 4,
    isActive: true,
  },
  // === CMS Hospital Compare Data (141 additional hospitals) ===
  {
    id: "cms-440003",
    metroId: "metro-nashville",
    name: "Highpoint Health-sumner With Ascension Saint Thoma",
    slug: "highpoint-health-sumner-with-ascension-saint-thoma",
    address: "555 Hartsville Pike",
    city: "Gallatin",
    stateCode: "TN",
    zipCode: "37066",
    location: { lat: 36.3833, lng: -86.4514 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    cmsOverallRating: 2,
    phone: "(615) 328-8888",
    isActive: true,
  },
  {
    id: "cms-440029",
    metroId: "metro-nashville",
    name: "Williamson Medical Center",
    slug: "williamson-medical-center",
    address: "4321 Carothers Parkway",
    city: "Franklin",
    stateCode: "TN",
    zipCode: "37067",
    location: { lat: 35.9476, lng: -86.8094 },
    hospitalType: "General Acute Care",
    ownership: "Government",
    hasEmergency: true,
    cmsOverallRating: 4,
    phone: "(615) 435-5000",
    isActive: true,
  },
  {
    id: "cms-440046",
    metroId: "metro-nashville",
    name: "Tristar Horizon Medical Center",
    slug: "tristar-horizon-medical-center",
    address: "111 Highway 70 East",
    city: "Dickson",
    stateCode: "TN",
    zipCode: "37055",
    location: { lat: 36.0752, lng: -87.3876 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    cmsOverallRating: 4,
    phone: "(615) 446-0446",
    isActive: true,
  },
  {
    id: "cms-440053",
    metroId: "metro-nashville",
    name: "Saint Thomas Rutherford Hospital",
    slug: "saint-thomas-rutherford-hospital",
    address: "1700 Medical Center Parkway",
    city: "Murfreesboro",
    stateCode: "TN",
    zipCode: "37129",
    location: { lat: 35.8685, lng: -86.372 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 2,
    phone: "(615) 396-4100",
    isActive: true,
  },
  {
    id: "cms-440059",
    metroId: "metro-nashville",
    name: "Cookeville Regional Medical Center",
    slug: "cookeville-regional-medical-center",
    address: "1 Medical Center Boulevard",
    city: "Cookeville",
    stateCode: "TN",
    zipCode: "38501",
    location: { lat: 36.1628, lng: -85.5016 },
    hospitalType: "General Acute Care",
    ownership: "Government",
    hasEmergency: true,
    cmsOverallRating: 2,
    phone: "(931) 783-2000",
    isActive: true,
  },
  {
    id: "cms-440065",
    metroId: "metro-nashville",
    name: "Tristar Northcrest Medical Center",
    slug: "tristar-northcrest-medical-center",
    address: "100 Northcrest Drive",
    city: "Springfield",
    stateCode: "TN",
    zipCode: "37172",
    location: { lat: 36.5094, lng: -86.885 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 3,
    phone: "(615) 384-2411",
    isActive: true,
  },
  {
    id: "cms-440073",
    metroId: "metro-nashville",
    name: "Maury Regional Hospital",
    slug: "maury-regional-hospital",
    address: "1224 Trotwood Ave",
    city: "Columbia",
    stateCode: "TN",
    zipCode: "38401",
    location: { lat: 35.615, lng: -87.0353 },
    hospitalType: "General Acute Care",
    ownership: "Government",
    hasEmergency: true,
    cmsOverallRating: 3,
    phone: "(931) 381-1111",
    isActive: true,
  },
  {
    id: "cms-440082",
    metroId: "metro-nashville",
    name: "Ascension Saint Thomas Hospital",
    slug: "ascension-saint-thomas-hospital",
    address: "4220 Harding Rd, Po Box 380",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37205",
    location: { lat: 36.1261, lng: -86.8625 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 3,
    phone: "(615) 222-2111",
    isActive: true,
  },
  {
    id: "cms-440111",
    metroId: "metro-nashville",
    name: "Metro Nashville General Hospital",
    slug: "metro-nashville-general-hospital",
    address: "1818 Albion Street",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37208",
    location: { lat: 36.1742, lng: -86.8096 },
    hospitalType: "General Acute Care",
    ownership: "Government",
    hasEmergency: true,
    phone: "(615) 341-4490",
    isActive: true,
  },
  {
    id: "cms-440137",
    metroId: "metro-nashville",
    name: "Vanderbilt Bedford Hospital",
    slug: "vanderbilt-bedford-hospital",
    address: "2835 Hwy 231 North",
    city: "Shelbyville",
    stateCode: "TN",
    zipCode: "37160",
    location: { lat: 35.484, lng: -86.461 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    phone: "(931) 685-5433",
    isActive: true,
  },
  {
    id: "cms-440150",
    metroId: "metro-nashville",
    name: "Tristar Summit Medical Center",
    slug: "tristar-summit-medical-center",
    address: "5655 Frist Blvd",
    city: "Hermitage",
    stateCode: "TN",
    zipCode: "37076",
    location: { lat: 36.1609, lng: -86.5897 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    cmsOverallRating: 2,
    phone: "(615) 316-3000",
    isActive: true,
  },
  {
    id: "cms-44017F",
    metroId: "metro-nashville",
    name: "Va Middle Tennessee Healthcare System - Murfreesboro",
    slug: "va-middle-tennessee-healthcare-system-murfreesboro",
    address: "3400 Lebanon Pike",
    city: "Murfreesboro",
    stateCode: "TN",
    zipCode: "37129",
    location: { lat: 35.8685, lng: -86.372 },
    hospitalType: "General Acute Care",
    ownership: "Unknown",
    hasEmergency: false,
    phone: "(615) 867-6000",
    isActive: true,
  },
  {
    id: "cms-44018F",
    metroId: "metro-nashville",
    name: "Va Middle Tennessee Healthcare System",
    slug: "va-middle-tennessee-healthcare-system",
    address: "1310 24th Avenue South",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37212",
    location: { lat: 36.1363, lng: -86.8042 },
    hospitalType: "General Acute Care",
    ownership: "Unknown",
    hasEmergency: true,
    cmsOverallRating: 5,
    phone: "(615) 327-5332",
    isActive: true,
  },
  {
    id: "cms-440193",
    metroId: "metro-nashville",
    name: "Vanderbilt Wilson County Hospital",
    slug: "vanderbilt-wilson-county-hospital",
    address: "1411 Baddour Parkway",
    city: "Lebanon",
    stateCode: "TN",
    zipCode: "37087",
    location: { lat: 36.2075, lng: -86.2947 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 4,
    phone: "(615) 444-2250",
    isActive: true,
  },
  {
    id: "cms-440194",
    metroId: "metro-nashville",
    name: "Tristar Hendersonville Medical Center",
    slug: "tristar-hendersonville-medical-center",
    address: "355 New Shackle Island Rd",
    city: "Hendersonville",
    stateCode: "TN",
    zipCode: "37075",
    location: { lat: 36.3115, lng: -86.6207 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    cmsOverallRating: 4,
    phone: "(615) 338-1000",
    isActive: true,
  },
  {
    id: "cms-440197",
    metroId: "metro-nashville",
    name: "Tristar Southern Hills Medical Center",
    slug: "tristar-southern-hills-medical-center",
    address: "391 Wallace Rd",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37211",
    location: { lat: 36.066, lng: -86.7225 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    cmsOverallRating: 4,
    phone: "(615) 781-4000",
    isActive: true,
  },
  {
    id: "cms-440218",
    metroId: "metro-nashville",
    name: "Saint Thomas Hospital for Spinal Surgery",
    slug: "saint-thomas-hospital-for-spinal-surgery",
    address: "2011 Murphy Avenue",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37203",
    location: { lat: 36.1513, lng: -86.7906 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: false,
    phone: "(615) 515-8200",
    isActive: true,
  },
  {
    id: "cms-440227",
    metroId: "metro-nashville",
    name: "Tristar Stonecrest Medical Center",
    slug: "tristar-stonecrest-medical-center",
    address: "200 Stonecrest Boulevard",
    city: "Smyrna",
    stateCode: "TN",
    zipCode: "37167",
    location: { lat: 35.964, lng: -86.518 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    cmsOverallRating: 3,
    phone: "(615) 768-2000",
    isActive: true,
  },
  {
    id: "cms-440231",
    metroId: "metro-nashville",
    name: "Trustpoint Hospital",
    slug: "trustpoint-hospital",
    address: "1009 North Thompson Lane",
    city: "Murfreesboro",
    stateCode: "TN",
    zipCode: "37129",
    location: { lat: 35.8685, lng: -86.372 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: false,
    phone: "(615) 867-1111",
    isActive: true,
  },
  {
    id: "cms-441301",
    metroId: "metro-nashville",
    name: "Highpoint Health-trousdale With Ascension Saint",
    slug: "highpoint-health-trousdale-with-ascension-saint",
    address: "500 Church Street",
    city: "Hartsville",
    stateCode: "TN",
    zipCode: "37074",
    location: { lat: 36.3907, lng: -86.1639 },
    hospitalType: "Critical Access",
    ownership: "Non-Profit",
    hasEmergency: true,
    phone: "(615) 374-2221",
    isActive: true,
  },
  {
    id: "cms-444007",
    metroId: "metro-nashville",
    name: "Rolling Hills Psychiatric Hospital",
    slug: "rolling-hills-psychiatric-hospital",
    address: "2014 Quail Hollow Circle",
    city: "Franklin",
    stateCode: "TN",
    zipCode: "37067",
    location: { lat: 35.9476, lng: -86.8094 },
    hospitalType: "Psychiatric",
    ownership: "Non-Profit",
    hasEmergency: true,
    phone: "(615) 226-4930",
    isActive: true,
  },
  {
    id: "cms-444014",
    metroId: "metro-nashville",
    name: "Middle Tn Mental Health Institute",
    slug: "middle-tn-mental-health-institute",
    address: "221 Stewarts Ferry Pike",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37214",
    location: { lat: 36.1601, lng: -86.6615 },
    hospitalType: "Psychiatric",
    ownership: "Government",
    hasEmergency: false,
    phone: "(615) 902-7565",
    isActive: true,
  },
  {
    id: "cms-444021",
    metroId: "metro-nashville",
    name: "Unity Psychiatric Care-columbia",
    slug: "unity-psychiatric-care-columbia",
    address: "1400 Rosewood Drive",
    city: "Columbia",
    stateCode: "TN",
    zipCode: "38401",
    location: { lat: 35.615, lng: -87.0353 },
    hospitalType: "Psychiatric",
    ownership: "For-Profit",
    hasEmergency: true,
    phone: "(931) 388-6573",
    isActive: true,
  },
  {
    id: "cms-444029",
    metroId: "metro-nashville",
    name: "Pinewood Springs",
    slug: "pinewood-springs",
    address: "1001 N James Campbell Blvd",
    city: "Columbia",
    stateCode: "TN",
    zipCode: "38401",
    location: { lat: 35.615, lng: -87.0353 },
    hospitalType: "Psychiatric",
    ownership: "For-Profit",
    hasEmergency: false,
    phone: "(931) 777-6000",
    isActive: true,
  },
  {
    id: "cms-444030",
    metroId: "metro-nashville",
    name: "Ascension Saint Thomas Behavioral Health Hospital",
    slug: "ascension-saint-thomas-behavioral-health-hospital",
    address: "300 Great Circle Road",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37228",
    location: { lat: 36.1932, lng: -86.8058 },
    hospitalType: "Psychiatric",
    ownership: "For-Profit",
    hasEmergency: false,
    phone: "(615) 813-1880",
    isActive: true,
  },
  {
    id: "cms-450018",
    metroId: "metro-houston",
    name: "University of Texas Medical Branch Galveston",
    slug: "university-of-texas-medical-branch-galveston",
    address: "301 University Boulevard",
    city: "Galveston",
    stateCode: "TX",
    zipCode: "77555",
    location: { lat: 29.313, lng: -94.7776 },
    hospitalType: "General Acute Care",
    ownership: "Government",
    hasEmergency: true,
    cmsOverallRating: 3,
    phone: "(409) 772-1011",
    isActive: true,
  },
  {
    id: "cms-450035",
    metroId: "metro-houston",
    name: "St Joseph Medical Center",
    slug: "st-joseph-medical-center",
    address: "1401 St. Joseph Parkway",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77002",
    location: { lat: 29.7545, lng: -95.363 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    cmsOverallRating: 2,
    phone: "(713) 757-1000",
    isActive: true,
  },
  {
    id: "cms-450097",
    metroId: "metro-houston",
    name: "Hca Houston Healthcare Southeast",
    slug: "hca-houston-healthcare-southeast",
    address: "4000 Spencer Hwy",
    city: "Pasadena",
    stateCode: "TX",
    zipCode: "77504",
    location: { lat: 29.6563, lng: -95.1881 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    cmsOverallRating: 3,
    phone: "(713) 359-1000",
    isActive: true,
  },
  {
    id: "cms-450184",
    metroId: "metro-houston",
    name: "Memorial Hermann Hospital System",
    slug: "memorial-hermann-hospital-system",
    address: "1635  North Loop West",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77008",
    location: { lat: 29.7914, lng: -95.4176 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 3,
    phone: "(713) 448-6796",
    isActive: true,
  },
  {
    id: "cms-450193",
    metroId: "metro-houston",
    name: "Baylor St Lukes Medical Center",
    slug: "baylor-st-lukes-medical-center",
    address: "6720 Bertner Ave, Ste Mc1-266",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77030",
    location: { lat: 29.7095, lng: -95.3985 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 3,
    phone: "(832) 355-1000",
    isActive: true,
  },
  {
    id: "cms-450222",
    metroId: "metro-houston",
    name: "Hca Houston Healthcare Conroe",
    slug: "hca-houston-healthcare-conroe",
    address: "504 Medical Center Blvd",
    city: "Conroe",
    stateCode: "TX",
    zipCode: "77304",
    location: { lat: 30.3495, lng: -95.5206 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    cmsOverallRating: 2,
    phone: "(936) 539-1111",
    isActive: true,
  },
  {
    id: "cms-450289",
    metroId: "metro-houston",
    name: "Harris Health",
    slug: "harris-health",
    address: "1504 Taub Loop",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77030",
    location: { lat: 29.7095, lng: -95.3985 },
    hospitalType: "General Acute Care",
    ownership: "Government",
    hasEmergency: true,
    cmsOverallRating: 3,
    phone: "(713) 873-2000",
    isActive: true,
  },
  {
    id: "cms-450330",
    metroId: "metro-houston",
    name: "Oakbend Medical Center",
    slug: "oakbend-medical-center",
    address: "1705 Jackson St",
    city: "Richmond",
    stateCode: "TX",
    zipCode: "77469",
    location: { lat: 29.5814, lng: -95.761 },
    hospitalType: "General Acute Care",
    ownership: "Government",
    hasEmergency: true,
    cmsOverallRating: 2,
    phone: "(281) 341-3000",
    isActive: true,
  },
  {
    id: "cms-450424",
    metroId: "metro-houston",
    name: "Houston Methodist Baytown Hospital",
    slug: "houston-methodist-baytown-hospital",
    address: "4401 Garth Road",
    city: "Baytown",
    stateCode: "TX",
    zipCode: "77521",
    location: { lat: 29.7946, lng: -94.9288 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 5,
    phone: "(281) 420-8600",
    isActive: true,
  },
  {
    id: "cms-450465",
    metroId: "metro-houston",
    name: "Matagorda Regional Medical Center",
    slug: "matagorda-regional-medical-center",
    address: "104 7th Street",
    city: "Bay City",
    stateCode: "TX",
    zipCode: "77414",
    location: { lat: 28.973, lng: -95.956 },
    hospitalType: "General Acute Care",
    ownership: "Government",
    hasEmergency: true,
    cmsOverallRating: 4,
    phone: "(979) 245-6383",
    isActive: true,
  },
  {
    id: "cms-450610",
    metroId: "metro-houston",
    name: "Memorial Hermann Memorial City Hospital",
    slug: "memorial-hermann-memorial-city-hospital",
    address: "921 Gessner",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77024",
    location: { lat: 29.7735, lng: -95.5172 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 3,
    phone: "(713) 242-3000",
    isActive: true,
  },
  {
    id: "cms-450617",
    metroId: "metro-houston",
    name: "Hca Houston Healthcare Clear Lake",
    slug: "hca-houston-healthcare-clear-lake",
    address: "500 W Medical Center Blvd",
    city: "Webster",
    stateCode: "TX",
    zipCode: "77598",
    location: { lat: 29.56, lng: -95.104 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    cmsOverallRating: 3,
    phone: "(281) 332-2511",
    isActive: true,
  },
  {
    id: "cms-450638",
    metroId: "metro-houston",
    name: "Hca Houston Healthcare Northwest",
    slug: "hca-houston-healthcare-northwest",
    address: "710 Cypress Creek Parkway",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77090",
    location: { lat: 29.9549, lng: -95.4433 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    cmsOverallRating: 3,
    phone: "(281) 440-1000",
    isActive: true,
  },
  {
    id: "cms-450644",
    metroId: "metro-houston",
    name: "Hca Houston Healthcare West",
    slug: "hca-houston-healthcare-west",
    address: "12141 Richmond Ave",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77082",
    location: { lat: 29.7242, lng: -95.6044 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    cmsOverallRating: 2,
    phone: "(281) 588-8080",
    isActive: true,
  },
  {
    id: "cms-450659",
    metroId: "metro-houston",
    name: "Hca Houston Healthcare Medical Center",
    slug: "hca-houston-healthcare-medical-center",
    address: "1313 Hermann Dr",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77004",
    location: { lat: 29.7195, lng: -95.3625 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    cmsOverallRating: 4,
    phone: "(713) 527-5019",
    isActive: true,
  },
  {
    id: "cms-450670",
    metroId: "metro-houston",
    name: "Hca Houston Healthcare Tomball",
    slug: "hca-houston-healthcare-tomball",
    address: "605 Holderrieth",
    city: "Tomball",
    stateCode: "TX",
    zipCode: "77375",
    location: { lat: 30.0893, lng: -95.6137 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    cmsOverallRating: 2,
    phone: "(281) 351-7500",
    isActive: true,
  },
  {
    id: "cms-450674",
    metroId: "metro-houston",
    name: "Womans Hospital of Texas,the",
    slug: "womans-hospital-of-texas-the",
    address: "7600 Fannin",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77054",
    location: { lat: 29.6917, lng: -95.3981 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    cmsOverallRating: 3,
    phone: "(713) 790-1234",
    isActive: true,
  },
  {
    id: "cms-450684",
    metroId: "metro-houston",
    name: "Memorial Hermann Northeast Hospital",
    slug: "memorial-hermann-northeast-hospital",
    address: "18951 Memorial North",
    city: "Humble",
    stateCode: "TX",
    zipCode: "77338",
    location: { lat: 29.999, lng: -95.2671 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 3,
    phone: "(281) 540-7700",
    isActive: true,
  },
  {
    id: "cms-450709",
    metroId: "metro-houston",
    name: "Houston Methodist Clear Lake Hospital",
    slug: "houston-methodist-clear-lake-hospital",
    address: "18300 St John Drive",
    city: "Nassau Bay",
    stateCode: "TX",
    zipCode: "77058",
    location: { lat: 29.5549, lng: -95.1007 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 5,
    phone: "(281) 333-5503",
    isActive: true,
  },
  {
    id: "cms-45074F",
    metroId: "metro-houston",
    name: "Houston Va Medical Center",
    slug: "houston-va-medical-center",
    address: "2002 Holcombe Blvd.",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77030",
    location: { lat: 29.7095, lng: -95.3985 },
    hospitalType: "General Acute Care",
    ownership: "Unknown",
    hasEmergency: true,
    cmsOverallRating: 4,
    phone: "(713) 794-7100",
    isActive: true,
  },
  {
    id: "cms-450774",
    metroId: "metro-houston",
    name: "Tops Surgical Specialty Hospital",
    slug: "tops-surgical-specialty-hospital",
    address: "17080 Red Oak Drive",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77090",
    location: { lat: 29.9549, lng: -95.4433 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: false,
    phone: "(281) 539-2900",
    isActive: true,
  },
  {
    id: "cms-450804",
    metroId: "metro-houston",
    name: "Texas Orthopedic Hospital",
    slug: "texas-orthopedic-hospital",
    address: "7401 South Main Street",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77030",
    location: { lat: 29.7095, lng: -95.3985 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    phone: "(713) 799-8600",
    isActive: true,
  },
  {
    id: "cms-450820",
    metroId: "metro-houston",
    name: "Houston Methodist Sugarland Hospital",
    slug: "houston-methodist-sugarland-hospital",
    address: "16655 Southwest Freeway",
    city: "Sugar Land",
    stateCode: "TX",
    zipCode: "77479",
    location: { lat: 29.567, lng: -95.6364 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 4,
    phone: "(281) 274-8000",
    isActive: true,
  },
  {
    id: "cms-450831",
    metroId: "metro-houston",
    name: "Surgery Specialty Hospitals of America Se Houston",
    slug: "surgery-specialty-hospitals-of-america-se-houston",
    address: "4301 B Vista",
    city: "Pasadena",
    stateCode: "TX",
    zipCode: "77504",
    location: { lat: 29.6563, lng: -95.1881 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    phone: "(713) 378-3000",
    isActive: true,
  },
  {
    id: "cms-450844",
    metroId: "metro-houston",
    name: "Houston Methodist Willowbrook Hospital",
    slug: "houston-methodist-willowbrook-hospital",
    address: "18220 State Highway 249",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77070",
    location: { lat: 29.9637, lng: -95.553 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 5,
    phone: "(281) 477-1000",
    isActive: true,
  },
  {
    id: "cms-450847",
    metroId: "metro-houston",
    name: "Memorial Hermann Katy Hospital",
    slug: "memorial-hermann-katy-hospital",
    address: "23900 Katy Freeway",
    city: "Katy",
    stateCode: "TX",
    zipCode: "77494",
    location: { lat: 29.783, lng: -95.804 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 3,
    phone: "(281) 392-1111",
    isActive: true,
  },
  {
    id: "cms-450848",
    metroId: "metro-houston",
    name: "Memorial Hermann Sugar Land Hospital",
    slug: "memorial-hermann-sugar-land-hospital",
    address: "17500 W Grand Parkway South",
    city: "Sugar Land",
    stateCode: "TX",
    zipCode: "77479",
    location: { lat: 29.567, lng: -95.6364 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 3,
    phone: "(281) 725-5000",
    isActive: true,
  },
  {
    id: "cms-450860",
    metroId: "metro-houston",
    name: "Sugar Land Surgical Hospital Llp",
    slug: "sugar-land-surgical-hospital-llp",
    address: "16906 Southwest Freeway",
    city: "Sugar Land",
    stateCode: "TX",
    zipCode: "77479",
    location: { lat: 29.567, lng: -95.6364 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    phone: "(281) 243-1000",
    isActive: true,
  },
  {
    id: "cms-450862",
    metroId: "metro-houston",
    name: "St Luke's the Woodlands Hospital",
    slug: "st-luke-s-the-woodlands-hospital",
    address: "17200 St Luke's Way",
    city: "The Woodlands",
    stateCode: "TX",
    zipCode: "77384",
    location: { lat: 30.204, lng: -95.482 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 4,
    phone: "(936) 266-4050",
    isActive: true,
  },
  {
    id: "cms-453304",
    metroId: "metro-houston",
    name: "Texas Childrens Hospital",
    slug: "texas-childrens-hospital",
    address: "6621 Fannin Street",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77030",
    location: { lat: 29.7095, lng: -95.3985 },
    hospitalType: "Children's",
    ownership: "Non-Profit",
    hasEmergency: true,
    phone: "(832) 824-1000",
    isActive: true,
  },
  {
    id: "cms-453309",
    metroId: "metro-houston",
    name: "Healthbridge Childrens's Hospital of Houston",
    slug: "healthbridge-childrens-s-hospital-of-houston",
    address: "2929 Woodland Park Drive",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77082",
    location: { lat: 29.7242, lng: -95.6044 },
    hospitalType: "Children's",
    ownership: "Non-Profit",
    hasEmergency: false,
    phone: "(281) 293-7774",
    isActive: true,
  },
  {
    id: "cms-453311",
    metroId: "metro-houston",
    name: "Shriners Hospitals for Children",
    slug: "shriners-hospitals-for-children",
    address: "815 Market Street",
    city: "Galveston",
    stateCode: "TX",
    zipCode: "77550",
    location: { lat: 29.2949, lng: -94.7905 },
    hospitalType: "Children's",
    ownership: "Non-Profit",
    hasEmergency: false,
    phone: "(409) 770-6600",
    isActive: true,
  },
  {
    id: "cms-454026",
    metroId: "metro-houston",
    name: "West Oaks Hospital",
    slug: "west-oaks-hospital",
    address: "6500 Hornwood",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77074",
    location: { lat: 29.6856, lng: -95.5194 },
    hospitalType: "Psychiatric",
    ownership: "For-Profit",
    hasEmergency: false,
    phone: "(713) 995-0909",
    isActive: true,
  },
  {
    id: "cms-454076",
    metroId: "metro-houston",
    name: "Harris County Psychiatric Center",
    slug: "harris-county-psychiatric-center",
    address: "2800 Macgregor Way",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77021",
    location: { lat: 29.6996, lng: -95.3517 },
    hospitalType: "Psychiatric",
    ownership: "Government",
    hasEmergency: false,
    phone: "(713) 741-5000",
    isActive: true,
  },
  {
    id: "cms-454107",
    metroId: "metro-houston",
    name: "Behavioral Hospital of Bellaire",
    slug: "behavioral-hospital-of-bellaire",
    address: "5314 Dashwood, Suite 200",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77081",
    location: { lat: 29.712, lng: -95.503 },
    hospitalType: "Psychiatric",
    ownership: "For-Profit",
    hasEmergency: false,
    phone: "(713) 600-9500",
    isActive: true,
  },
  {
    id: "cms-454108",
    metroId: "metro-houston",
    name: "Cypress Creek Hospital",
    slug: "cypress-creek-hospital",
    address: "17750 Cali Drive",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77090",
    location: { lat: 29.9549, lng: -95.4433 },
    hospitalType: "Psychiatric",
    ownership: "For-Profit",
    hasEmergency: true,
    phone: "(281) 586-7600",
    isActive: true,
  },
  {
    id: "cms-454118",
    metroId: "metro-houston",
    name: "Lone Star Behavioral Health Cypress",
    slug: "lone-star-behavioral-health-cypress",
    address: "16303 Grant Road",
    city: "Cypress",
    stateCode: "TX",
    zipCode: "77429",
    location: { lat: 29.953, lng: -95.664 },
    hospitalType: "Psychiatric",
    ownership: "For-Profit",
    hasEmergency: false,
    phone: "(281) 516-6186",
    isActive: true,
  },
  {
    id: "cms-454131",
    metroId: "metro-houston",
    name: "Westpark Springs Llc",
    slug: "westpark-springs-llc",
    address: "6902 S Peek Road",
    city: "Richmond",
    stateCode: "TX",
    zipCode: "77407",
    location: { lat: 29.693, lng: -95.712 },
    hospitalType: "Psychiatric",
    ownership: "For-Profit",
    hasEmergency: true,
    phone: "(832) 535-2770",
    isActive: true,
  },
  {
    id: "cms-454135",
    metroId: "metro-houston",
    name: "Houston Behavioral Healthcare Hospital Llc",
    slug: "houston-behavioral-healthcare-hospital-llc",
    address: "2801 Gessner Road",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77080",
    location: { lat: 29.821, lng: -95.536 },
    hospitalType: "Psychiatric",
    ownership: "For-Profit",
    hasEmergency: false,
    phone: "(832) 834-7710",
    isActive: true,
  },
  {
    id: "cms-454136",
    metroId: "metro-houston",
    name: "Oceans Behavioral Hospital of Katy",
    slug: "oceans-behavioral-hospital-of-katy",
    address: "455 Park Grove Lane",
    city: "Katy",
    stateCode: "TX",
    zipCode: "77450",
    location: { lat: 29.79, lng: -95.7364 },
    hospitalType: "Psychiatric",
    ownership: "For-Profit",
    hasEmergency: false,
    phone: "(281) 492-8888",
    isActive: true,
  },
  {
    id: "cms-454139",
    metroId: "metro-houston",
    name: "Sun Behavioral Houston",
    slug: "sun-behavioral-houston",
    address: "7601 Fannin Street",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77054",
    location: { lat: 29.6917, lng: -95.3981 },
    hospitalType: "Psychiatric",
    ownership: "For-Profit",
    hasEmergency: true,
    phone: "(713) 795-5025",
    isActive: true,
  },
  {
    id: "cms-454144",
    metroId: "metro-houston",
    name: "Woodland Springs",
    slug: "woodland-springs",
    address: "15860 Old Conroe Road",
    city: "Conroe",
    stateCode: "TX",
    zipCode: "77384",
    location: { lat: 30.204, lng: -95.482 },
    hospitalType: "Psychiatric",
    ownership: "For-Profit",
    hasEmergency: false,
    phone: "(936) 270-7520",
    isActive: true,
  },
  {
    id: "cms-454147",
    metroId: "metro-houston",
    name: "Oceans Behavioral Hospital of Pasadena",
    slug: "oceans-behavioral-hospital-of-pasadena",
    address: "4001 Preston Avenue",
    city: "Pasadena",
    stateCode: "TX",
    zipCode: "77505",
    location: { lat: 29.6355, lng: -95.1536 },
    hospitalType: "Psychiatric",
    ownership: "For-Profit",
    hasEmergency: false,
    phone: "(832) 619-8836",
    isActive: true,
  },
  {
    id: "cms-454156",
    metroId: "metro-houston",
    name: "Voyages Behavioral Health of Sugar Land",
    slug: "voyages-behavioral-health-of-sugar-land",
    address: "11931 Highway 6 South",
    city: "Sugar Land",
    stateCode: "TX",
    zipCode: "77498",
    location: { lat: 29.605, lng: -95.567 },
    hospitalType: "Psychiatric",
    ownership: "For-Profit",
    hasEmergency: false,
    phone: "(281) 896-0112",
    isActive: true,
  },
  {
    id: "cms-454158",
    metroId: "metro-houston",
    name: "Voyages Behavioral Health of Conroe",
    slug: "voyages-behavioral-health-of-conroe",
    address: "1317 S Loop 336 West",
    city: "Conroe",
    stateCode: "TX",
    zipCode: "77304",
    location: { lat: 30.3495, lng: -95.5206 },
    hospitalType: "Psychiatric",
    ownership: "For-Profit",
    hasEmergency: false,
    phone: "(936) 242-0409",
    isActive: true,
  },
  {
    id: "cms-670008",
    metroId: "metro-houston",
    name: "Memorial Hermann Houston Physicians Hospital",
    slug: "memorial-hermann-houston-physicians-hospital",
    address: "333 N Texas Avenue, Suite 1000",
    city: "Webster",
    stateCode: "TX",
    zipCode: "77598",
    location: { lat: 29.56, lng: -95.104 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    phone: "(281) 335-1700",
    isActive: true,
  },
  {
    id: "cms-670031",
    metroId: "metro-houston",
    name: "St Luke's Patients Medical Center",
    slug: "st-luke-s-patients-medical-center",
    address: "4600 East Sam Houston Parkway South",
    city: "Pasadena",
    stateCode: "TX",
    zipCode: "77505",
    location: { lat: 29.6355, lng: -95.1536 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    cmsOverallRating: 4,
    phone: "(281) 487-0700",
    isActive: true,
  },
  {
    id: "cms-670053",
    metroId: "metro-houston",
    name: "St Luke's Sugar Land Hospital",
    slug: "st-luke-s-sugar-land-hospital",
    address: "1317 Lake Pointe Parkway",
    city: "Sugar Land",
    stateCode: "TX",
    zipCode: "77478",
    location: { lat: 29.6268, lng: -95.6269 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 3,
    phone: "(281) 637-7000",
    isActive: true,
  },
  {
    id: "cms-670059",
    metroId: "metro-houston",
    name: "Chi St Lukes Lakeside Hospital",
    slug: "chi-st-lukes-lakeside-hospital",
    address: "17400 St Lukes Way",
    city: "The Woodlands",
    stateCode: "TX",
    zipCode: "77384",
    location: { lat: 30.204, lng: -95.482 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    phone: "(936) 266-4055",
    isActive: true,
  },
  {
    id: "cms-670075",
    metroId: "metro-houston",
    name: "St Luke's Hospital at the Vintage",
    slug: "st-luke-s-hospital-at-the-vintage",
    address: "20171 Chasewood Park Drive",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77070",
    location: { lat: 29.9637, lng: -95.553 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 4,
    phone: "(832) 534-5000",
    isActive: true,
  },
  {
    id: "cms-670077",
    metroId: "metro-houston",
    name: "Houston Methodist West Hospital",
    slug: "houston-methodist-west-hospital",
    address: "18500 Katy Freeway",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77094",
    location: { lat: 29.774, lng: -95.6741 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 4,
    phone: "(832) 522-1000",
    isActive: true,
  },
  {
    id: "cms-670093",
    metroId: "metro-houston",
    name: "Aspire Hospital",
    slug: "aspire-hospital",
    address: "2006 South Loop 336 West, Suite 500",
    city: "Conroe",
    stateCode: "TX",
    zipCode: "77304",
    location: { lat: 30.3495, lng: -95.5206 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: false,
    phone: "(936) 647-3500",
    isActive: true,
  },
  {
    id: "cms-670102",
    metroId: "metro-houston",
    name: "Ad Hospital East, Llc",
    slug: "ad-hospital-east-llc",
    address: "12950 East Freeway, Suite 100",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77015",
    location: { lat: 29.7607, lng: -95.1771 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    phone: "(281) 863-2100",
    isActive: true,
  },
  {
    id: "cms-670106",
    metroId: "metro-houston",
    name: "Hca Houston Healthcare Pearland",
    slug: "hca-houston-healthcare-pearland",
    address: "11100 Shadow Creek Parkway",
    city: "Pearland",
    stateCode: "TX",
    zipCode: "77584",
    location: { lat: 29.5252, lng: -95.3271 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    cmsOverallRating: 3,
    phone: "(713) 770-7000",
    isActive: true,
  },
  {
    id: "cms-670109",
    metroId: "metro-houston",
    name: "Altus Baytown Hospital",
    slug: "altus-baytown-hospital",
    address: "1626 W Baker Road",
    city: "Baytown",
    stateCode: "TX",
    zipCode: "77521",
    location: { lat: 29.7946, lng: -94.9288 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    phone: "(281) 837-7600",
    isActive: true,
  },
  {
    id: "cms-670115",
    metroId: "metro-houston",
    name: "Cleveland Emergency Hospital",
    slug: "cleveland-emergency-hospital",
    address: "8901 Fm 1960 Bypass Rd W, Suite 105",
    city: "Humble",
    stateCode: "TX",
    zipCode: "77338",
    location: { lat: 29.999, lng: -95.2671 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    phone: "(281) 592-5400",
    isActive: true,
  },
  {
    id: "cms-670122",
    metroId: "metro-houston",
    name: "Houston Methodist the Woodlands Hospital",
    slug: "houston-methodist-the-woodlands-hospital",
    address: "17201 Interstate 45 South",
    city: "The Woodlands",
    stateCode: "TX",
    zipCode: "77385",
    location: { lat: 30.23, lng: -95.411 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 5,
    phone: "(936) 270-2000",
    isActive: true,
  },
  {
    id: "cms-670135",
    metroId: "metro-houston",
    name: "Altus Houston Hospital, Lp",
    slug: "altus-houston-hospital-lp",
    address: "6011 W Sam Houston Pkwy South",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77072",
    location: { lat: 29.693, lng: -95.572 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    phone: "(713) 773-0556",
    isActive: true,
  },
  {
    id: "cms-670266",
    metroId: "metro-houston",
    name: "Townsen Memorial Hospital",
    slug: "townsen-memorial-hospital",
    address: "1475 Fm 1960 Bypass E",
    city: "Humble",
    stateCode: "TX",
    zipCode: "77338",
    location: { lat: 29.999, lng: -95.2671 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    phone: "(281) 369-9001",
    isActive: true,
  },
  {
    id: "cms-670267",
    metroId: "metro-houston",
    name: "The Woodlands Specialty Hospital",
    slug: "the-woodlands-specialty-hospital",
    address: "25440 Interstate 45 North",
    city: "Spring",
    stateCode: "TX",
    zipCode: "77386",
    location: { lat: 30.1727, lng: -95.3559 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    phone: "(281) 602-8160",
    isActive: true,
  },
  {
    id: "cms-670314",
    metroId: "metro-houston",
    name: "St Michaels Medical Hospital Llc",
    slug: "st-michaels-medical-hospital-llc",
    address: "16000 Southwest Freeway, Suite 100",
    city: "Sugar Land",
    stateCode: "TX",
    zipCode: "77479",
    location: { lat: 29.567, lng: -95.6364 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    phone: "(281) 980-4357",
    isActive: true,
  },
  {
    id: "cms-670320",
    metroId: "metro-houston",
    name: "East Houston Medical Center",
    slug: "east-houston-medical-center",
    address: "15149 Wallisville Road",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77049",
    location: { lat: 29.807, lng: -95.169 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    phone: "(281) 988-9800",
    isActive: true,
  },
  {
    id: "cms-670342",
    metroId: "metro-houston",
    name: "Houston Methodist Cypress Hospital",
    slug: "houston-methodist-cypress-hospital",
    address: "24500 Northwest Fwy",
    city: "Cypress",
    stateCode: "TX",
    zipCode: "77429",
    location: { lat: 29.953, lng: -95.664 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    phone: "(346) 618-1506",
    isActive: true,
  },
  {
    id: "cms-030014",
    metroId: "metro-phoenix",
    name: "Honor Health John C. Lincoln Medical Center",
    slug: "honor-health-john-c-lincoln-medical-center",
    address: "250 East Dunlap Avenue",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85020",
    location: { lat: 33.5676, lng: -112.0558 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 3,
    phone: "(602) 943-2381",
    isActive: true,
  },
  {
    id: "cms-030022",
    metroId: "metro-phoenix",
    name: "Valleywise Health Medical Center",
    slug: "valleywise-health-medical-center",
    address: "2601 East Roosevelt Street",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85008",
    location: { lat: 33.4609, lng: -112.0076 },
    hospitalType: "General Acute Care",
    ownership: "Government",
    hasEmergency: false,
    cmsOverallRating: 3,
    phone: "(602) 344-5011",
    isActive: true,
  },
  {
    id: "cms-030024",
    metroId: "metro-phoenix",
    name: "St Josephs Hospital and Medical Center",
    slug: "st-josephs-hospital-and-medical-center",
    address: "350 West Thomas Road",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85013",
    location: { lat: 33.512, lng: -112.0829 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 3,
    phone: "(602) 406-8225",
    isActive: true,
  },
  {
    id: "cms-030030",
    metroId: "metro-phoenix",
    name: "Abrazo Central Campus",
    slug: "abrazo-central-campus",
    address: "2000 West Bethany Home Road",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85015",
    location: { lat: 33.5073, lng: -112.1029 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    cmsOverallRating: 2,
    phone: "(602) 249-0212",
    isActive: true,
  },
  {
    id: "cms-030036",
    metroId: "metro-phoenix",
    name: "Chandler Regional Medical Center",
    slug: "chandler-regional-medical-center",
    address: "1955 West Frye Road",
    city: "Chandler",
    stateCode: "AZ",
    zipCode: "85224",
    location: { lat: 33.2964, lng: -111.86 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 4,
    phone: "(480) 728-3000",
    isActive: true,
  },
  {
    id: "cms-030037",
    metroId: "metro-phoenix",
    name: "Honorhealth Tempe Medical Center",
    slug: "honorhealth-tempe-medical-center",
    address: "1800 East Van Buren Street",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85006",
    location: { lat: 33.4575, lng: -112.045 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    phone: "(602) 251-8156",
    isActive: true,
  },
  {
    id: "cms-030038",
    metroId: "metro-phoenix",
    name: "Honorhealth Scottsdale Osborn Medical Center",
    slug: "honorhealth-scottsdale-osborn-medical-center",
    address: "7400 East Osborn Road",
    city: "Scottsdale",
    stateCode: "AZ",
    zipCode: "85251",
    location: { lat: 33.4941, lng: -111.9237 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    cmsOverallRating: 3,
    phone: "(480) 882-4004",
    isActive: true,
  },
  {
    id: "cms-030061",
    metroId: "metro-phoenix",
    name: "Banner Boswell Medical Center",
    slug: "banner-boswell-medical-center",
    address: "13632 N 99th Ave",
    city: "Sun City",
    stateCode: "AZ",
    zipCode: "85351",
    location: { lat: 33.6156, lng: -112.281 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 3,
    phone: "(623) 832-4000",
    isActive: true,
  },
  {
    id: "cms-030065",
    metroId: "metro-phoenix",
    name: "Banner Desert Medical Center",
    slug: "banner-desert-medical-center",
    address: "1400 South  Dobson Road",
    city: "Mesa",
    stateCode: "AZ",
    zipCode: "85202",
    location: { lat: 33.3916, lng: -111.8612 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 2,
    phone: "(480) 412-3000",
    isActive: true,
  },
  {
    id: "cms-030078",
    metroId: "metro-phoenix",
    name: "Phoenix Indian Medical Center",
    slug: "phoenix-indian-medical-center",
    address: "4212 North 16th Street",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85016",
    location: { lat: 33.5073, lng: -112.0283 },
    hospitalType: "General Acute Care",
    ownership: "Government",
    hasEmergency: false,
    phone: "(602) 263-1200",
    isActive: true,
  },
  {
    id: "cms-030083",
    metroId: "metro-phoenix",
    name: "Abrazo Scottsdale Campus",
    slug: "abrazo-scottsdale-campus",
    address: "3929 East Bell Road",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85032",
    location: { lat: 33.612, lng: -111.9833 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    cmsOverallRating: 2,
    phone: "(602) 923-5609",
    isActive: true,
  },
  {
    id: "cms-030087",
    metroId: "metro-phoenix",
    name: "Honorhealth Scottsdale Shea Medical Center",
    slug: "honorhealth-scottsdale-shea-medical-center",
    address: "9003 East Shea Boulevard",
    city: "Scottsdale",
    stateCode: "AZ",
    zipCode: "85260",
    location: { lat: 33.622, lng: -111.887 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    cmsOverallRating: 3,
    phone: "(480) 323-3000",
    isActive: true,
  },
  {
    id: "cms-030088",
    metroId: "metro-phoenix",
    name: "Banner Baywood Medical Center",
    slug: "banner-baywood-medical-center",
    address: "6644 East Baywood Avenue",
    city: "Mesa",
    stateCode: "AZ",
    zipCode: "85206",
    location: { lat: 33.3816, lng: -111.7192 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 2,
    phone: "(480) 321-2000",
    isActive: true,
  },
  {
    id: "cms-030089",
    metroId: "metro-phoenix",
    name: "Banner Thunderbird Medical Center",
    slug: "banner-thunderbird-medical-center",
    address: "5555 West Thunderbird Road",
    city: "Glendale",
    stateCode: "AZ",
    zipCode: "85306",
    location: { lat: 33.61, lng: -112.18 },
    hospitalType: "General Acute Care",
    ownership: "Government",
    hasEmergency: false,
    cmsOverallRating: 3,
    phone: "(602) 865-4470",
    isActive: true,
  },
  {
    id: "cms-030092",
    metroId: "metro-phoenix",
    name: "Honorhealth Deer Valley Medical Center",
    slug: "honorhealth-deer-valley-medical-center",
    address: "19829 North 27th Avenue",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85027",
    location: { lat: 33.6645, lng: -112.099 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 2,
    phone: "(623) 879-6100",
    isActive: true,
  },
  {
    id: "cms-030093",
    metroId: "metro-phoenix",
    name: "Banner Del E. Webb Medical Center",
    slug: "banner-del-e-webb-medical-center",
    address: "14502 West Meeker Boulevard",
    city: "Sun City West",
    stateCode: "AZ",
    zipCode: "85375",
    location: { lat: 33.6708, lng: -112.2766 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 3,
    phone: "(623) 524-4000",
    isActive: true,
  },
  {
    id: "cms-030094",
    metroId: "metro-phoenix",
    name: "Abrazo Arrowhead Hospital",
    slug: "abrazo-arrowhead-hospital",
    address: "18701 North 67th Avenue",
    city: "Glendale",
    stateCode: "AZ",
    zipCode: "85308",
    location: { lat: 33.63, lng: -112.18 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    cmsOverallRating: 2,
    phone: "(623) 561-1000",
    isActive: true,
  },
  {
    id: "cms-030103",
    metroId: "metro-phoenix",
    name: "Mayo Clinic Hospital",
    slug: "mayo-clinic-hospital",
    address: "5777 East Mayo Boulevard",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85054",
    location: { lat: 33.662, lng: -111.949 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 5,
    phone: "(480) 342-4201",
    isActive: true,
  },
  {
    id: "cms-030105",
    metroId: "metro-phoenix",
    name: "Banner Heart Hospital",
    slug: "banner-heart-hospital",
    address: "6750 East Baywood Avenue",
    city: "Mesa",
    stateCode: "AZ",
    zipCode: "85206",
    location: { lat: 33.3816, lng: -111.7192 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: false,
    cmsOverallRating: 3,
    phone: "(480) 854-5050",
    isActive: true,
  },
  {
    id: "cms-030107",
    metroId: "metro-phoenix",
    name: "Arizona Spine and Joint Hospital",
    slug: "arizona-spine-and-joint-hospital",
    address: "4620 East Baseline Road",
    city: "Mesa",
    stateCode: "AZ",
    zipCode: "85206",
    location: { lat: 33.3816, lng: -111.7192 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: false,
    phone: "(480) 832-4770",
    isActive: true,
  },
  {
    id: "cms-030108",
    metroId: "metro-phoenix",
    name: "The Core Institute Specialty Hosp",
    slug: "the-core-institute-specialty-hosp",
    address: "6501 North 19th Avenue",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85015",
    location: { lat: 33.5073, lng: -112.1029 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: false,
    phone: "(602) 795-6020",
    isActive: true,
  },
  {
    id: "cms-030110",
    metroId: "metro-phoenix",
    name: "Abrazo West Campus",
    slug: "abrazo-west-campus",
    address: "13677 West Mcdowell Road",
    city: "Goodyear",
    stateCode: "AZ",
    zipCode: "85395",
    location: { lat: 33.53, lng: -112.39 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    cmsOverallRating: 2,
    phone: "(623) 882-1970",
    isActive: true,
  },
  {
    id: "cms-030112",
    metroId: "metro-phoenix",
    name: "Arizona Orthopedic and Surgical Specialty Hospital",
    slug: "arizona-orthopedic-and-surgical-specialty-hospital",
    address: "750 North 40th Street",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85008",
    location: { lat: 33.4609, lng: -112.0076 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: false,
    phone: "(480) 603-9000",
    isActive: true,
  },
  {
    id: "cms-030115",
    metroId: "metro-phoenix",
    name: "Banner Estrella Medical Center",
    slug: "banner-estrella-medical-center",
    address: "9201 West Thomas Road",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85037",
    location: { lat: 33.4479, lng: -112.1779 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 3,
    phone: "(623) 327-4000",
    isActive: true,
  },
  {
    id: "cms-030119",
    metroId: "metro-phoenix",
    name: "Mercy Gilbert Medical Center",
    slug: "mercy-gilbert-medical-center",
    address: "3555 South Val Vista Drive",
    city: "Gilbert",
    stateCode: "AZ",
    zipCode: "85297",
    location: { lat: 33.278, lng: -111.74 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 5,
    phone: "(480) 728-8000",
    isActive: true,
  },
  {
    id: "cms-030121",
    metroId: "metro-phoenix",
    name: "Honorhealth Mountain Vista Medical Center",
    slug: "honorhealth-mountain-vista-medical-center",
    address: "1301 South Crismon Road",
    city: "Mesa",
    stateCode: "AZ",
    zipCode: "85209",
    location: { lat: 33.393, lng: -111.664 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    cmsOverallRating: 2,
    phone: "(480) 358-6100",
    isActive: true,
  },
  {
    id: "cms-030122",
    metroId: "metro-phoenix",
    name: "Banner Gateway Medical Center",
    slug: "banner-gateway-medical-center",
    address: "1900 North Higley Road",
    city: "Gilbert",
    stateCode: "AZ",
    zipCode: "85234",
    location: { lat: 33.3786, lng: -111.7374 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 4,
    phone: "(480) 543-2000",
    isActive: true,
  },
  {
    id: "cms-030123",
    metroId: "metro-phoenix",
    name: "Honorhealth Scottsdale Thompson Peak Med Ctr",
    slug: "honorhealth-scottsdale-thompson-peak-med-ctr",
    address: "7400 East Thompson Peak Parkway",
    city: "Scottsdale",
    stateCode: "AZ",
    zipCode: "85255",
    location: { lat: 33.6697, lng: -111.8563 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 4,
    phone: "(480) 324-7001",
    isActive: true,
  },
  {
    id: "cms-03012F",
    metroId: "metro-phoenix",
    name: "Phoenix Va Medical Center",
    slug: "phoenix-va-medical-center",
    address: "650 E. Indian School Road",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85012",
    location: { lat: 33.5073, lng: -112.0733 },
    hospitalType: "General Acute Care",
    ownership: "Unknown",
    hasEmergency: true,
    cmsOverallRating: 5,
    phone: "(602) 222-6444",
    isActive: true,
  },
  {
    id: "cms-030130",
    metroId: "metro-phoenix",
    name: "Banner Ironwood Medical Center",
    slug: "banner-ironwood-medical-center",
    address: "37000 North Gantzel Road",
    city: "Queen Creek",
    stateCode: "AZ",
    zipCode: "85140",
    location: { lat: 33.283, lng: -111.543 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 3,
    phone: "(480) 394-4000",
    isActive: true,
  },
  {
    id: "cms-030134",
    metroId: "metro-phoenix",
    name: "Banner Goldfield Medical Center",
    slug: "banner-goldfield-medical-center",
    address: "2050 West Southern Avenue",
    city: "Apache Junction",
    stateCode: "AZ",
    zipCode: "85120",
    location: { lat: 33.4057, lng: -111.5491 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    phone: "(480) 733-3300",
    isActive: true,
  },
  {
    id: "cms-030138",
    metroId: "metro-phoenix",
    name: "City of Hope Cancer Center Phoenix",
    slug: "city-of-hope-cancer-center-phoenix",
    address: "14200 West Celebrate Life Way",
    city: "Goodyear",
    stateCode: "AZ",
    zipCode: "85338",
    location: { lat: 33.4364, lng: -112.3583 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: false,
    cmsOverallRating: 5,
    phone: "(623) 207-3000",
    isActive: true,
  },
  {
    id: "cms-030139",
    metroId: "metro-phoenix",
    name: "Dignity Health Arizona General Hospital",
    slug: "dignity-health-arizona-general-hospital",
    address: "9130 East Elliot Road",
    city: "Mesa",
    stateCode: "AZ",
    zipCode: "85212",
    location: { lat: 33.361, lng: -111.617 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 3,
    phone: "(480) 410-4500",
    isActive: true,
  },
  {
    id: "cms-030146",
    metroId: "metro-phoenix",
    name: "Honorhealth Sonoran Crossing Medical Center",
    slug: "honorhealth-sonoran-crossing-medical-center",
    address: "33400 North 32nd Avenue",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85085",
    location: { lat: 33.746, lng: -112.042 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 4,
    phone: "(480) 882-4327",
    isActive: true,
  },
  {
    id: "cms-030147",
    metroId: "metro-phoenix",
    name: "Banner Ocotillo Medical Center",
    slug: "banner-ocotillo-medical-center",
    address: "1405 South Alma School Road",
    city: "Chandler",
    stateCode: "AZ",
    zipCode: "85286",
    location: { lat: 33.34, lng: -111.906 },
    hospitalType: "General Acute Care",
    ownership: "Non-Profit",
    hasEmergency: true,
    cmsOverallRating: 2,
    phone: "(480) 256-7000",
    isActive: true,
  },
  {
    id: "cms-030153",
    metroId: "metro-phoenix",
    name: "East Valley Er & Hospital",
    slug: "east-valley-er-hospital",
    address: "5656 South Power Rd",
    city: "Gilbert",
    stateCode: "AZ",
    zipCode: "85295",
    location: { lat: 33.29, lng: -111.77 },
    hospitalType: "General Acute Care",
    ownership: "For-Profit",
    hasEmergency: true,
    phone: "(713) 660-0557",
    isActive: true,
  },
  {
    id: "cms-031300",
    metroId: "metro-phoenix",
    name: "Wickenburg Community Hospital",
    slug: "wickenburg-community-hospital",
    address: "520 Rose Lane",
    city: "Wickenburg",
    stateCode: "AZ",
    zipCode: "85390",
    location: { lat: 33.9686, lng: -112.7295 },
    hospitalType: "Critical Access",
    ownership: "Non-Profit",
    hasEmergency: true,
    phone: "(928) 684-5421",
    isActive: true,
  },
  {
    id: "cms-033302",
    metroId: "metro-phoenix",
    name: "Phoenix Children's Hospital",
    slug: "phoenix-children-s-hospital",
    address: "1919 East Thomas Road",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85016",
    location: { lat: 33.5073, lng: -112.0283 },
    hospitalType: "Children's",
    ownership: "Non-Profit",
    hasEmergency: false,
    phone: "(602) 933-1000",
    isActive: true,
  },
  {
    id: "cms-034004",
    metroId: "metro-phoenix",
    name: "Banner Behavioral Health Hospital",
    slug: "banner-behavioral-health-hospital",
    address: "7575 East Earll Drive",
    city: "Scottsdale",
    stateCode: "AZ",
    zipCode: "85251",
    location: { lat: 33.4941, lng: -111.9237 },
    hospitalType: "Psychiatric",
    ownership: "Non-Profit",
    hasEmergency: false,
    phone: "(480) 448-7500",
    isActive: true,
  },
  {
    id: "cms-034013",
    metroId: "metro-phoenix",
    name: "College Medical Center Phoenix",
    slug: "college-medical-center-phoenix",
    address: "1800 East Van Buren",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85006",
    location: { lat: 33.4575, lng: -112.045 },
    hospitalType: "Psychiatric",
    ownership: "For-Profit",
    hasEmergency: false,
    phone: "(602) 251-8535",
    isActive: true,
  },
  {
    id: "cms-034020",
    metroId: "metro-phoenix",
    name: "Haven Behavioral Hospital of Phoenix",
    slug: "haven-behavioral-hospital-of-phoenix",
    address: "1201 South 7th Avenue, Suite 200",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85007",
    location: { lat: 33.441, lng: -112.096 },
    hospitalType: "Psychiatric",
    ownership: "For-Profit",
    hasEmergency: false,
    phone: "(623) 236-2000",
    isActive: true,
  },
  {
    id: "cms-034021",
    metroId: "metro-phoenix",
    name: "Arizona State Hospital",
    slug: "arizona-state-hospital",
    address: "2500 East Van Buren Street",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85008",
    location: { lat: 33.4609, lng: -112.0076 },
    hospitalType: "Psychiatric",
    ownership: "Government",
    hasEmergency: false,
    phone: "(602) 220-6000",
    isActive: true,
  },
  {
    id: "cms-034024",
    metroId: "metro-phoenix",
    name: "Aurora Behavioral Health System",
    slug: "aurora-behavioral-health-system",
    address: "6015 West Peoria  Avenue",
    city: "Glendale",
    stateCode: "AZ",
    zipCode: "85302",
    location: { lat: 33.5543, lng: -112.198 },
    hospitalType: "Psychiatric",
    ownership: "For-Profit",
    hasEmergency: false,
    phone: "(623) 344-4400",
    isActive: true,
  },
  {
    id: "cms-034026",
    metroId: "metro-phoenix",
    name: "Valley Hospital",
    slug: "valley-hospital",
    address: "3550 East Pinchot Avenue",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85018",
    location: { lat: 33.5073, lng: -111.9833 },
    hospitalType: "Psychiatric",
    ownership: "For-Profit",
    hasEmergency: false,
    phone: "(602) 952-3900",
    isActive: true,
  },
  {
    id: "cms-034028",
    metroId: "metro-phoenix",
    name: "Aurora Behavioral Healthcare-tempe",
    slug: "aurora-behavioral-healthcare-tempe",
    address: "6350 South Maple Avenue",
    city: "Tempe",
    stateCode: "AZ",
    zipCode: "85283",
    location: { lat: 33.364, lng: -111.9252 },
    hospitalType: "Psychiatric",
    ownership: "For-Profit",
    hasEmergency: false,
    phone: "(480) 345-5400",
    isActive: true,
  },
  {
    id: "cms-034029",
    metroId: "metro-phoenix",
    name: "Oasis Behavioral Health Hospital",
    slug: "oasis-behavioral-health-hospital",
    address: "2190 North Grace Boulevard, Building a",
    city: "Chandler",
    stateCode: "AZ",
    zipCode: "85225",
    location: { lat: 33.3213, lng: -111.8127 },
    hospitalType: "Psychiatric",
    ownership: "For-Profit",
    hasEmergency: false,
    phone: "(480) 917-9301",
    isActive: true,
  },
  {
    id: "cms-034031",
    metroId: "metro-phoenix",
    name: "Quail Run Behavioral Health",
    slug: "quail-run-behavioral-health",
    address: "2545 West Quail Avenue",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85027",
    location: { lat: 33.6645, lng: -112.099 },
    hospitalType: "Psychiatric",
    ownership: "Non-Profit",
    hasEmergency: false,
    phone: "(602) 455-5700",
    isActive: true,
  },
  {
    id: "cms-034032",
    metroId: "metro-phoenix",
    name: "Copper Springs East- Gilbert",
    slug: "copper-springs-east-gilbert",
    address: "10550 West Mcdowell Road",
    city: "Avondale",
    stateCode: "AZ",
    zipCode: "85392",
    location: { lat: 33.458, lng: -112.363 },
    hospitalType: "Psychiatric",
    ownership: "For-Profit",
    hasEmergency: true,
    phone: "(480) 565-3035",
    isActive: true,
  },
  {
    id: "cms-034034",
    metroId: "metro-phoenix",
    name: "Destiny Springs Healthcare",
    slug: "destiny-springs-healthcare",
    address: "17300 North Dysart Road",
    city: "Surprise",
    stateCode: "AZ",
    zipCode: "85378",
    location: { lat: 33.624, lng: -112.32 },
    hospitalType: "Psychiatric",
    ownership: "For-Profit",
    hasEmergency: false,
    phone: "(623) 233-3000",
    isActive: true,
  },
  {
    id: "cms-034035",
    metroId: "metro-phoenix",
    name: "Avenir Behavioral Health Center",
    slug: "avenir-behavioral-health-center",
    address: "16561 North Parkview Place",
    city: "Surprise",
    stateCode: "AZ",
    zipCode: "85374",
    location: { lat: 33.649, lng: -112.349 },
    hospitalType: "Psychiatric",
    ownership: "For-Profit",
    hasEmergency: false,
    phone: "(480) 229-9894",
    isActive: true,
  },
  {
    id: "cms-034038",
    metroId: "metro-phoenix",
    name: "Phoenix Medical Psychiatric Hospital, Llc",
    slug: "phoenix-medical-psychiatric-hospital-llc",
    address: "1346 East Mcdowell Road",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85006",
    location: { lat: 33.4575, lng: -112.045 },
    hospitalType: "Psychiatric",
    ownership: "For-Profit",
    hasEmergency: false,
    phone: "(833) 312-0320",
    isActive: true,
  },
  {
    id: "cms-034040",
    metroId: "metro-phoenix",
    name: "Via Linda Behavioral Hospital",
    slug: "via-linda-behavioral-hospital",
    address: "9160 East Horseshoe Rd",
    city: "Scottsdale",
    stateCode: "AZ",
    zipCode: "85258",
    location: { lat: 33.5441, lng: -111.8946 },
    hospitalType: "Psychiatric",
    ownership: "For-Profit",
    hasEmergency: false,
    phone: "(480) 476-7000",
    isActive: true,
  },
  {
    id: "cms-034041",
    metroId: "metro-phoenix",
    name: "Agave Ridge Behavioral Hospital",
    slug: "agave-ridge-behavioral-hospital",
    address: "3322 South Ellsworth Road",
    city: "Mesa",
    stateCode: "AZ",
    zipCode: "85212",
    location: { lat: 33.361, lng: -111.617 },
    hospitalType: "Psychiatric",
    ownership: "For-Profit",
    hasEmergency: false,
    phone: "(615) 861-6000",
    isActive: true,
  },
];

// Sample listings near Nashville hospitals
export const SAMPLE_LISTINGS: Listing[] = [
  {
    id: "list-1",
    metroId: "metro-nashville",
    source: "manual",
    title: "Modern 1BR in Midtown — Walk to Vanderbilt",
    description: "Fully furnished 1-bedroom apartment in the heart of Midtown Nashville. 10-minute walk to Vanderbilt Medical Center. W/D in unit, free parking spot included.",
    propertyType: "apartment",
    location: { lat: 36.1520, lng: -86.7970 },
    address: "1800 Broadway",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37203",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 720,
    priceMonthly: 1850,
    isFurnished: true,
    leaseMinMonths: 3,
    allowsPets: true,
    hasParking: true,
    hasInUnitLaundry: true,
    amenities: ["pool", "gym", "balcony", "doorman"],
    primaryImageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop",
    imageCount: 8,
    listingQualityScore: 85,
    status: "active",
    isVerified: true,
    isFeatured: false,
  },
  {
    id: "list-2",
    metroId: "metro-nashville",
    source: "manual",
    title: "Cozy Studio near Music Row — Furnished",
    description: "Charming furnished studio on Music Row. Quick commute to all major Nashville hospitals. Perfect for travel nurses on 13-week contracts.",
    propertyType: "studio",
    location: { lat: 36.1495, lng: -86.7928 },
    address: "33 Music Square W",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37203",
    bedrooms: 0,
    bathrooms: 1,
    sqft: 475,
    priceMonthly: 1350,
    isFurnished: true,
    leaseMinMonths: 1,
    allowsPets: false,
    hasParking: true,
    hasInUnitLaundry: false,
    amenities: ["gym", "rooftop"],
    primaryImageUrl: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
    imageCount: 5,
    listingQualityScore: 70,
    status: "active",
    isVerified: true,
    isFeatured: false,
  },
  {
    id: "list-3",
    metroId: "metro-nashville",
    source: "manual",
    title: "Spacious 2BR in Sylvan Park — 5 min to St. Thomas",
    description: "Beautiful 2-bedroom home in the quiet Sylvan Park neighborhood. 5-minute drive to Ascension Saint Thomas West. Fenced backyard, pet friendly.",
    propertyType: "house",
    location: { lat: 36.1380, lng: -86.8360 },
    address: "4512 Nevada Ave",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37209",
    bedrooms: 2,
    bathrooms: 1.5,
    sqft: 1100,
    priceMonthly: 2200,
    isFurnished: false,
    leaseMinMonths: 6,
    allowsPets: true,
    hasParking: true,
    hasInUnitLaundry: true,
    amenities: ["backyard", "storage", "porch"],
    primaryImageUrl: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=600&fit=crop",
    imageCount: 12,
    listingQualityScore: 60,
    status: "active",
    isVerified: false,
    isFeatured: false,
  },
  {
    id: "list-4",
    metroId: "metro-nashville",
    source: "manual",
    title: "Luxury 1BR in The Gulch — All Amenities",
    description: "Upscale 1-bedroom in The Gulch with stunning downtown views. Walking distance to multiple hospitals. Full amenity package.",
    propertyType: "apartment",
    location: { lat: 36.1510, lng: -86.7870 },
    address: "600 12th Ave S",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37203",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 800,
    priceMonthly: 2400,
    isFurnished: true,
    leaseMinMonths: 3,
    allowsPets: true,
    hasParking: true,
    hasInUnitLaundry: true,
    amenities: ["pool", "gym", "rooftop", "concierge", "balcony"],
    primaryImageUrl: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop",
    imageCount: 15,
    listingQualityScore: 90,
    status: "active",
    isVerified: true,
    isFeatured: false,
  },
  {
    id: "list-5",
    metroId: "metro-nashville",
    source: "manual",
    title: "Affordable Room in West End — Near Hospitals",
    description: "Private room in shared house near West End. 2 miles from Vanderbilt. All utilities included. Great for residents on a budget.",
    propertyType: "room",
    location: { lat: 36.1465, lng: -86.8140 },
    address: "2800 West End Ave",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37203",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 280,
    priceMonthly: 850,
    isFurnished: true,
    leaseMinMonths: 1,
    allowsPets: false,
    hasParking: true,
    hasInUnitLaundry: true,
    amenities: ["utilities-included", "wifi"],
    primaryImageUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&h=600&fit=crop",
    imageCount: 4,
    listingQualityScore: 65,
    status: "active",
    isVerified: false,
    isFeatured: false,
  },
  {
    id: "list-6",
    metroId: "metro-nashville",
    source: "manual",
    title: "2BR Townhouse in Berry Hill — Short Term OK",
    description: "Nice townhouse in Berry Hill with private garage. 10 min to all midtown hospitals. Short-term lease available for travel nurses.",
    propertyType: "townhouse",
    location: { lat: 36.1200, lng: -86.7650 },
    address: "2610 Berry Hill Dr",
    city: "Nashville",
    stateCode: "TN",
    zipCode: "37204",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1250,
    priceMonthly: 1950,
    isFurnished: false,
    leaseMinMonths: 3,
    allowsPets: true,
    hasParking: true,
    hasInUnitLaundry: true,
    amenities: ["garage", "patio", "storage"],
    primaryImageUrl: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800&h=600&fit=crop",
    imageCount: 9,
    listingQualityScore: 55,
    status: "active",
    isVerified: true,
    isFeatured: false,
  },
  // Houston
  {
    id: "list-7",
    metroId: "metro-houston",
    source: "manual",
    title: "Furnished 1BR in Texas Medical Center Area",
    description: "Fully furnished apartment steps from the Texas Medical Center. Perfect for travel nurses and residents. All utilities included.",
    propertyType: "apartment",
    location: { lat: 29.7130, lng: -95.3960 },
    address: "6700 Main St",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77030",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 680,
    priceMonthly: 1650,
    isFurnished: true,
    leaseMinMonths: 1,
    allowsPets: false,
    hasParking: true,
    hasInUnitLaundry: false,
    amenities: ["pool", "gym", "utilities-included"],
    primaryImageUrl: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&h=600&fit=crop",
    imageCount: 6,
    listingQualityScore: 80,
    status: "active",
    isVerified: true,
    isFeatured: false,
  },
  {
    id: "list-8",
    metroId: "metro-houston",
    source: "manual",
    title: "Modern 2BR in Museum District — Near TMC",
    description: "Spacious 2-bedroom in the Museum District. 5 minutes to Texas Medical Center. Open floor plan with updated kitchen.",
    propertyType: "apartment",
    location: { lat: 29.7228, lng: -95.3904 },
    address: "4100 Montrose Blvd",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77006",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1050,
    priceMonthly: 2100,
    isFurnished: false,
    leaseMinMonths: 6,
    allowsPets: true,
    hasParking: true,
    hasInUnitLaundry: true,
    amenities: ["pool", "gym", "balcony", "storage"],
    primaryImageUrl: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&h=600&fit=crop",
    imageCount: 10,
    listingQualityScore: 70,
    status: "active",
    isVerified: true,
    isFeatured: false,
  },
  {
    id: "list-9",
    metroId: "metro-houston",
    source: "manual",
    title: "Studio in Rice Village — Walk to Med Center",
    description: "Cozy studio in Rice Village. Walking distance to Houston Methodist and Memorial Hermann TMC. Furnished with month-to-month lease.",
    propertyType: "studio",
    location: { lat: 29.7160, lng: -95.4089 },
    address: "2500 University Blvd",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77005",
    bedrooms: 0,
    bathrooms: 1,
    sqft: 450,
    priceMonthly: 1250,
    isFurnished: true,
    leaseMinMonths: 1,
    allowsPets: false,
    hasParking: true,
    hasInUnitLaundry: false,
    amenities: ["gym", "rooftop", "wifi"],
    primaryImageUrl: "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&h=600&fit=crop",
    imageCount: 5,
    listingQualityScore: 75,
    status: "active",
    isVerified: false,
    isFeatured: false,
  },
  {
    id: "list-10",
    metroId: "metro-houston",
    source: "manual",
    title: "Private Room in Hermann Park Area",
    description: "Private room in a shared house near Hermann Park. Very close to all TMC hospitals. Quiet neighborhood, great for night shift workers.",
    propertyType: "room",
    location: { lat: 29.7140, lng: -95.3870 },
    address: "1900 Hermann Dr",
    city: "Houston",
    stateCode: "TX",
    zipCode: "77004",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 300,
    priceMonthly: 850,
    isFurnished: true,
    leaseMinMonths: 1,
    allowsPets: false,
    hasParking: true,
    hasInUnitLaundry: true,
    amenities: ["utilities-included", "wifi", "backyard"],
    primaryImageUrl: "https://images.unsplash.com/photo-1598928506311-c55ez637a3c4?w=800&h=600&fit=crop",
    imageCount: 4,
    listingQualityScore: 60,
    status: "active",
    isVerified: false,
    isFeatured: false,
  },
  // Phoenix
  {
    id: "list-11",
    metroId: "metro-phoenix",
    source: "manual",
    title: "Furnished 1BR in Scottsdale — Near HonorHealth",
    description: "Stylish furnished 1-bedroom apartment in downtown Scottsdale. Short walk to HonorHealth Scottsdale Osborn. Resort-style amenities.",
    propertyType: "apartment",
    location: { lat: 33.4795, lng: -111.9260 },
    address: "7300 E Indian School Rd",
    city: "Scottsdale",
    stateCode: "AZ",
    zipCode: "85251",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 750,
    priceMonthly: 1700,
    isFurnished: true,
    leaseMinMonths: 3,
    allowsPets: true,
    hasParking: true,
    hasInUnitLaundry: true,
    amenities: ["pool", "gym", "spa", "balcony"],
    primaryImageUrl: "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&h=600&fit=crop",
    imageCount: 8,
    listingQualityScore: 85,
    status: "active",
    isVerified: true,
    isFeatured: false,
  },
  {
    id: "list-12",
    metroId: "metro-phoenix",
    source: "manual",
    title: "2BR Condo near Banner University Medical Center",
    description: "Updated 2-bedroom condo in Roosevelt Row arts district. 5 minutes to Banner University Medical Center. W/D in unit.",
    propertyType: "condo",
    location: { lat: 33.4530, lng: -112.0640 },
    address: "725 N 3rd St",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85004",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 980,
    priceMonthly: 1900,
    isFurnished: false,
    leaseMinMonths: 6,
    allowsPets: true,
    hasParking: true,
    hasInUnitLaundry: true,
    amenities: ["pool", "gym", "rooftop"],
    primaryImageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
    imageCount: 11,
    listingQualityScore: 65,
    status: "active",
    isVerified: true,
    isFeatured: false,
  },
  {
    id: "list-13",
    metroId: "metro-phoenix",
    source: "manual",
    title: "Affordable Studio in Tempe — Furnished",
    description: "Budget-friendly furnished studio in Tempe near the Light Rail. Easy access to all major Phoenix hospitals. Utilities included.",
    propertyType: "studio",
    location: { lat: 33.4255, lng: -111.9400 },
    address: "600 S College Ave",
    city: "Tempe",
    stateCode: "AZ",
    zipCode: "85281",
    bedrooms: 0,
    bathrooms: 1,
    sqft: 420,
    priceMonthly: 1100,
    isFurnished: true,
    leaseMinMonths: 1,
    allowsPets: false,
    hasParking: false,
    hasInUnitLaundry: false,
    amenities: ["gym", "utilities-included", "wifi"],
    primaryImageUrl: "https://images.unsplash.com/photo-1630699144867-37acec97df5a?w=800&h=600&fit=crop",
    imageCount: 4,
    listingQualityScore: 70,
    status: "active",
    isVerified: false,
    isFeatured: false,
  },
  {
    id: "list-14",
    metroId: "metro-phoenix",
    source: "manual",
    title: "3BR House in North Phoenix — Near Mayo Clinic",
    description: "Spacious 3-bedroom house in a quiet North Phoenix neighborhood. 10-minute drive to Mayo Clinic Hospital. Large backyard, pet friendly.",
    propertyType: "house",
    location: { lat: 33.6400, lng: -111.9700 },
    address: "5500 E Deer Valley Dr",
    city: "Phoenix",
    stateCode: "AZ",
    zipCode: "85054",
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1600,
    priceMonthly: 2400,
    isFurnished: false,
    leaseMinMonths: 6,
    allowsPets: true,
    hasParking: true,
    hasInUnitLaundry: true,
    amenities: ["backyard", "garage", "patio", "storage"],
    primaryImageUrl: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop",
    imageCount: 14,
    listingQualityScore: 60,
    status: "active",
    isVerified: true,
    isFeatured: false,
  },
];
